image:
  repository: 134517981306.dkr.ecr.eu-west-1.amazonaws.com/openremote/manager
  tag: demo

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 120
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 120
  periodSeconds: 5

or:
  env:
    - name: OR_SETUP_TYPE
      value: "demo"
