package org.openremote.test.rules;

import org.openremote.model.*;
import org.openremote.model.asset.*;
import elemental.json.*;

global java.util.logging.Logger LOG;

rule "Living Room All"
when
  $e: AssetState(name == "Living Room")
then
  return;
end

rule "Kitchen All"
when
  $e: AssetState(name == "Kitchen")
then
  return;
end

rule "Kitchen Integer Attributes"
when
  $e: AssetState(name == "Kitchen", attributeType == AttributeType.INTEGER)
then
  return;
end

rule "Living Room Thermostat"
when
  $e: AssetState(name == "Living Room Thermostat")
then
  return;
end

rule "Living Room Comfort Temperature"
when
  $e: AssetState(name == "Living Room Thermostat", attributeName == "comfortTemperature")
then
  return;
end

rule "Living Room as Parent"
when
    AssetState(parentName == "Living Room")
then
    return;
end

rule "Boolean Attributes"
when
    AssetState(attributeType == AttributeType.BOOLEAN)
then
  return;
end

rule "String Attributes"
when
    AssetState(attributeType == AttributeType.STRING)
then
  return;
end

rule "JSON Number value types"
when
    AssetState(value != null, value.type == JsonType.NUMBER)
then
    return;
end

rule "Current Asset Update"
when
    AssetState(processingStatus != AssetState.ProcessingStatus.COMPLETED)
then
    return;
end

rule "Parent Type Residence"
when
    AssetState(parentType == AssetType.RESIDENCE)
then
    return;
end

rule "Asset Type Room"
when
    AssetState(type == AssetType.ROOM)
then
    return;
end