package org.openremote.test.rules;

import org.openremote.model.*;

declare CallCounter
  count : int
end

rule "Insert Counter Fact"
when
    not $counter:CallCounter()
then
    // Insert Call Counter
    CallCounter counter = new CallCounter();
    insert(counter);
end

rule "TestRuleFiring"
when
	$e: AttributeStateChange( entityName == RuleExecutionLoggerTest.TEST_ENTITY_ID, attribute.name == RuleExecutionLoggerTest.TEST_ATTRIBUTE_NAME)
	$counter : CallCounter()
then
    // Update call count fact
end

