name: Get version details
description: Resolves the current base-, with qualifier and release version

outputs:
  version:
    description: The base project version without qualifiers (like -SNAPSHOT)
    value: ${{ steps.get-version-details.outputs.version }}
  version_with_qualifier:
    description: The complete version string including any qualifiers (e.g., -SNAPSHOT)
    value: ${{ steps.get-version-details.outputs.version_with_qualifier }}
  is_release:
    description: Whether this is a release
    value: ${{ steps.get-version-details.outputs.is_release }}

runs:
  using: composite
  steps:
    - name: Set up JDK 21 and Gradle cache
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: "temurin"
        java-version: 21
        cache: "gradle"

    - name: Get version details
      id: get-version-details
      shell: bash
      run: |
        set -o pipefail # exit build with error when pipes fail
        ./gradlew currentVersion | tee /tmp/currentVersion
        versionWithQualifier=$(grep "Project version" /tmp/currentVersion | sed 's#Project version: ##')
        version=$(sed -E 's#-.+##' <<< $versionWithQualifier)
        isRelease=false
        if [ "$version" == "$versionWithQualifier" ]; then
          isRelease=true
        fi
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "version_with_qualifier=$versionWithQualifier" >> $GITHUB_OUTPUT
        echo "is_release=$isRelease" >> $GITHUB_OUTPUT
