version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "openremote/openremote"

  # Maintain npm/Yarn dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown: # To be inline with the npmMinimalAgeGate setting in the .yarnrc.yml file
      default-days: 7
      exclude:
        - "@openremote/*"

  # Maintain Java dependencies for the Gradle multi-project build.
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
