changelog:
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - Breaking Changes
    - title: 🎉 New features
      labels:
        - Feature
    - title: ⭐ Enhancements
      labels:
        - Enhancement
    - title: 🐞 Bug fixes
      labels:
        - Bug
    - title: 📝 Documentation
      labels:
        - Documentation
    - title: Other changes
      labels:
        - "*"
