apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  region: eu-west-1

serviceAccount:
  create: false
  name: aws-load-balancer-controller

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 2
