# ---------------------------------------------------------------------------------------------------------------------
#
# CloudFormation Template for creating an separate EBS volume for storing OpenRemote data.
#
# ---------------------------------------------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an EBS data volume for storing OpenRemote data.'
Parameters:
  Host:
    Description: FQDN for host
    Type: String
  AvailabilityZone:
    Description: Availability zone where the EBS data volume needs to be created
    Type: String
  DiskSize:
    Description: Data EBS volume size in GB
    Type: Number
    Default: 16
  SnapshotId:
    Description: Snapshot ID to create the EBS data volume based of an existing snapshot
    Type: String
    Default: ""

Conditions:
  IsSnapshotProvided: !Not [!Equals [!Ref SnapshotId, ""]]

Resources:
  DataVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      Size: !Ref DiskSize
      VolumeType: gp3
      SnapshotId: !If [IsSnapshotProvided, !Ref SnapshotId, !Ref 'AWS::NoValue']
      Tags:
        - Key: Name
          Value: !Sub ${Host}/data
  