// TODO Fix this

package org.openremote.agent.test.rules;

import java.util.concurrent.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.io.*;
import org.openremote.agent.sensor.*;

global org.openremote.agent.command.Commands commands;
global org.openremote.agent.rules.RulePersistence persistence;

declare SensorState
  @role(event)
end

rule "-PSB: Init"
salience 10
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", persistence.readData("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE","--:--"));
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.inc", "OFF");
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.dec", "OFF");
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL.inc", "OFF");
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL.dec", "OFF");
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE.inc", "OFF");
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE.dec", "OFF");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP",persistence.readData("SETTINGS_COMFORT_TARGET_TEMP","20.0\u00B0"));
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.inc","OFF");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.dec","OFF");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP","19.5\u00B0");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.inc","OFF");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.dec","OFF");
  commands.execute("NEXT_EVENT",persistence.readData("NEXT_EVENT","-")); // Possible values are "-", "Departure", "Arrive"
  commands.execute("PRESENCE_LAST_DETECTED_TIME","-"); // hh:mm
  commands.execute("PRESENCE_DETECTED_LATCHED","No"); // Latches for 15mins
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.0");
  commands.execute("UI_ECO_SCORE", "0");
  commands.execute("ACTUATOR_TARGET_TEMP", "16");
  commands.execute("WINDOW_STATE","Closed");
  commands.execute("LEGACY_UI_ADVICE_SHOWN", "OFF");
  commands.execute("HEATING_DISABLED", "No");
  commands.execute("LEGACY_UI_ADVICE_TEXT", "You're doing great!");
  commands.execute("VACATION_DAYS.inc", "OFF");
  commands.execute("VACATION_DAYS.dec", "OFF");
  commands.execute("VACATION_DAYS", persistence.readData("VACATION_DAYS", "0"));
  commands.execute("LEGACY_UI_ECO_SCORE_CUMULATIVE",persistence.readData("LEGACY_UI_ECO_SCORE_CUMULATIVE", "0"));
  commands.execute("LEGACY_UI_ECO_SCORE_CUMULATIVE_SLIDER", persistence.readData("LEGACY_UI_ECO_SCORE_CUMULATIVE_SLIDER", "0"));
  commands.execute("ACTUAL_TIME_ARRIVAL", persistence.readData("ACTUAL_TIME_ARRIVAL","-"));
  commands.execute("ACTUAL_TIME_DEPARTURE", persistence.readData("ACTUAL_TIME_DEPARTURE","-"));
  commands.execute("LEGACY_UI_ROOM_NAME",persistence.readData("LEGACY_UI_ROOM_NAME", "OpenRemote"));
  commands.execute("LEGACY_UI_BACKGROUND_IMAGE_ARRIVAL", "on");
  commands.execute("LEGACY_UI_BACKGROUND_IMAGE_DEPARTURE", "off");
end

rule "-PSB: Init ETA when empty"
salience 9
when
  SensorState(sensorName matches "UI_ESTIMATED_TIME_ARRIVAL.*", $s: sensorName, value=="")
then
  commands.execute($s, persistence.readData($s, "09:00"));
end

rule "-PSB: Init ETD when empty"
salience 8
when
  SensorState(sensorName matches "UI_ESTIMATED_TIME_DEPARTURE.*", $s: sensorName, value=="")
then
  commands.execute($s, persistence.readData($s, "17:00"));
end

rule "--Show timers"
salience 10
// timer(int:100)
when
        SensorState(sensorName=="TIME_CURRENT_DAY_OF_WEEK", $a:value!="N/A")
        SensorState(sensorName=="TIME_DAY_OF_MONTH", $b:value!="N/A")
        SensorState(sensorName=="TIME_HH:MM:SS", $d:value!="N/A")
        SensorState(sensorName=="TIME_MONTH_IN_YEAR", $c:value!="N/A")
        SensorState(sensorName=="TIME_DAY_NAME_IN_WEEK", value!="N/A")
then
  LOG.info("Sensor clock is:          "+$a+" "+$b+" "+$c+" "+$d);
  LOG.info("Drools SessionClock() is: "+(new java.util.Date(drools.getWorkingMemory().getSessionClock().getCurrentTime())).toString());
end

rule "-PSB: LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE Inc"
  timer(int:300ms) // debounce & protect double click
when
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $v: value)
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.inc" , value == "ON")
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", util.shiftTime($v.toString(), 5));
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.inc", "off");
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.dec", "OFF");
end

rule "-PSB: UI_ESTIMATED_TIME_ARRIVAL Inc"
  timer(int:300ms) // debounce & protect double click
when
  SensorState(sensorName == "UI_ESTIMATED_TIME_ARRIVAL", $v: value)
  SensorState(sensorName == "UI_ESTIMATED_TIME_ARRIVAL.inc" , value == "ON")
then
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL", util.shiftTime($v.toString(), 5));
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL.inc", "off");
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL.dec", "OFF");
end

rule "-PSB: UI_ESTIMATED_TIME_DEPARTURE Inc"
  timer(int:300ms) // debounce & protect double click
when
  SensorState(sensorName == "UI_ESTIMATED_TIME_DEPARTURE", $v: value)
  SensorState(sensorName == "UI_ESTIMATED_TIME_DEPARTURE.inc" , value == "ON")
then
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE", util.shiftTime($v.toString(), 5));
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE.inc", "off");
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE.dec", "OFF");
end

rule "-PSB: LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE Dec"
  timer(int:300ms)
when
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $v: value)
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.dec" , value == "ON")
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", util.shiftTime($v.toString(), -15));
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.inc", "OFF");
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.dec", "off");
end

rule "-PSB: UI_ESTIMATED_TIME_ARRIVAL Dec"
  timer(int:300ms)
when
  SensorState(sensorName == "UI_ESTIMATED_TIME_ARRIVAL", $v: value)
  SensorState(sensorName == "UI_ESTIMATED_TIME_ARRIVAL.dec" , value == "ON")
then
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL", util.shiftTime($v.toString(), -15));
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL.inc", "OFF");
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL.dec", "off");
end

rule "-PSB: UI_ESTIMATED_TIME_DEPARTURE Dec"
  timer(int:300ms)
when
  SensorState(sensorName == "UI_ESTIMATED_TIME_DEPARTURE", $v: value)
  SensorState(sensorName == "UI_ESTIMATED_TIME_DEPARTURE.dec" , value == "ON")
then
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE", util.shiftTime($v.toString(), -15));
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE.inc", "OFF");
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE.dec", "off");
end

rule "PSB: MANUAL_SCHEDULE_CHANGE_COUNT_ change counter"
  timer(int: 30s) // Wait 30s to mark user's schedule change
when
(
  SensorState($s:sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.inc" , value == "off") ||
  SensorState($s:sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.dec" , value == "off") ||
  SensorState($s:sensorName == "UI_ESTIMATED_TIME_ARRIVAL.inc" , value == "off") ||
  SensorState($s:sensorName == "UI_ESTIMATED_TIME_ARRIVAL.dec" , value == "off") ||
  SensorState($s:sensorName == "UI_ESTIMATED_TIME_DEPARTURE.inc" , value == "off") ||
  SensorState($s:sensorName == "UI_ESTIMATED_TIME_DEPARTURE.dec" , value == "off")
)
then
  // off - changed by user
  // OFF - idle state after restart
  commands.execute($s, "OFF");
  int cnt = 0;
  try{
    cnt = Integer.parseInt(persistence.readData("MANUAL_SCHEDULE_CHANGE_COUNT_0","0"));
  }finally{
    cnt += 1;
    persistence.writeData("MANUAL_SCHEDULE_CHANGE_COUNT_0", cnt);
  }
end

rule "PSB: set departure time on manual LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE change"
  salience 10
  timer(int: 300ms)
when
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $v: value)
(
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.inc" , value == "ON") ||
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE.dec" , value == "ON") ||
  SensorState(sensorName == "UI_ESTIMATED_TIME_DEPARTURE.inc", value == "ON") ||
  SensorState(sensorName == "UI_ESTIMATED_TIME_DEPARTURE.dec", value == "ON")
)
  SensorState(sensorName == "NEXT_EVENT", value == "-")
then
  commands.execute("NEXT_EVENT", "Departure");
end

rule "PSB: SETTINGS_COMFORT_TARGET_TEMP inc"
  timer(int:300ms)
when
  SensorState(sensorName == "SETTINGS_COMFORT_TARGET_TEMP", $v: value, eval(util.parseDouble(value) < 24))
  SensorState(sensorName == "SETTINGS_COMFORT_TARGET_TEMP.inc" , value == "ON")
then
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.inc","off");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.dec","OFF");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP", util.shiftDouble($v.toString(), 0.5, "\u00B0"));
end

rule "PSB: SETTINGS_COMFORT_TARGET_TEMP dec"
  timer(int:300ms)
when
  SensorState(sensorName == "SETTINGS_COMFORT_TARGET_TEMP", $v: value, eval(util.parseDouble(value) > 18))
  SensorState(sensorName == "SETTINGS_COMFORT_TARGET_TEMP.dec" , value == "ON")
then
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.inc","OFF");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.dec","off");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP", util.shiftDouble($v.toString(), -0.5, "\u00B0"));
end

rule "PSB: SETTINGS_COMFORT_TARGET_TEMP INC/dec" // needed when change on the boundary
  salience -10
  timer(int:300ms)
when
  SensorState(sensorName == "SETTINGS_COMFORT_TARGET_TEMP.inc" , value == "ON")
then
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.inc","off");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.dec","OFF");
end

rule "PSB: SETTINGS_COMFORT_TARGET_TEMP inc/DEC" // needed when change on the boundary
  salience -10
  timer(int:300ms)
when
  SensorState(sensorName == "SETTINGS_COMFORT_TARGET_TEMP.dec" , value == "ON")
then
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.inc","OFF");
  commands.execute("SETTINGS_COMFORT_TARGET_TEMP.dec","off");
end

rule "PSB: CURRENT_COMFORT_TARGET_TEMP inc"
  timer(int:300ms)
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP", $v: value, eval(util.parseDouble(value) <26))
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.inc" , value == "ON")
then
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.inc","off");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.dec","OFF"); // Do not increase change counter
  commands.execute("CURRENT_COMFORT_TARGET_TEMP",   util.shiftDouble($v.toString(), 0.5, "\u00B0"));
end

rule "PSB: CURRENT_COMFORT_TARGET_TEMP dec"
  timer(int:300ms)
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP", $v: value, eval(util.parseDouble(value) > 16)) // Lower temp limit
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.dec" , value == "ON")
then
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.inc","OFF");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.dec","off");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP", util.shiftDouble($v.toString(), -0.5, "\u00B0"));
end

rule "PSB: CURRENT_COMFORT_TARGET_TEMP INC/dec" // needed when on the boundary and in summer
  salience -10
  timer(int:300ms)
when
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.inc" , value == "ON")
then
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.inc","off");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.dec","OFF");
end

rule "PSB: CURRENT_COMFORT_TARGET_TEMP inc/DEC" // needed when on the boundary and in summer
  salience -10
  timer(int:300ms)
when
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.dec" , value == "ON")
then
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.inc","OFF");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP.dec","off");
end

rule "PSB: CURRENT_COMFORT_TARGET_TEMP change counter"
  timer(int: 30s) // Wait 30s to mark user's temperature change
when
(
  SensorState($s:sensorName == "CURRENT_COMFORT_TARGET_TEMP.inc" , value == "off") ||
  SensorState($s:sensorName == "CURRENT_COMFORT_TARGET_TEMP.dec" , value == "off") ||
  SensorState($s:sensorName == "SETTINGS_COMFORT_TARGET_TEMP.inc" , value == "off") ||
  SensorState($s:sensorName == "SETTINGS_COMFORT_TARGET_TEMP.dec" , value == "off")
)
then
  // off - changed by user
  // OFF - idle state after restart
  commands.execute($s, "OFF");
  int cnt = 0;
  try{
    cnt = Integer.parseInt(persistence.readData("MANUAL_SET_TEMP_COUNT_PER_WEEK_0","0"));
  }finally{
    cnt += 1;
    persistence.writeData("MANUAL_SET_TEMP_COUNT_PER_WEEK_0", cnt);
  }
end

rule "PSB: CURRENT_COMFORT_TARGET_TEMP change summer"
salience 10
when
  SensorState(sensorName=="HEATING_DISABLED", value=="Yes")
(
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.inc" , $s: sensorName, value == "ON") ||
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.dec", $s: sensorName, value == "ON")
)
then
  commands.execute($s, "OFF");
end

rule "PSB: set departure on manual TEMPERATURE change after expected attendance"
salience 10
  timer(int:300ms)
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName == "LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $et: value)
(
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.inc" , value == "ON") ||
  SensorState(sensorName == "CURRENT_COMFORT_TARGET_TEMP.dec" , value == "ON")
)
  SensorState(sensorName == "NEXT_EVENT", value == "-")
then
  // Set departure time when temp manually adjusted after leave
  commands.execute("NEXT_EVENT", "Departure");
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", util.shiftTime($et.toString(), 60));
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE", util.shiftTime($et.toString(), 60));
end

rule "-PSB: Move ETA to ET at midnight"
when
  SensorState(sensorName=="TIME_DAY_NAME_IN_WEEK", $e:value)
  SensorState(sensorName=="TIME_HH:MM:SS",$h:value,eval(util.parseTimestamp(value) >= util.parseTimestamp("00:02"))) // Wait 2 minutes to be sure that $e is OK
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_ARRIVAL."+$e), eval(util.parseTimestamp(value) > util.parseTimestamp($h)), $va:value)
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_DEPARTURE."+$e), $vd: value)
  SensorState(sensorName=="NEXT_EVENT", value=="-")
  SensorState(sensorName=="VACATION_DAYS", eval(Integer.parseInt(value.toString())==0))
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $va.toString());
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL", $va.toString());
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE", $vd.toString());
  commands.execute("NEXT_EVENT", "Arrive");
end

rule "-Move ETA ETD for current day"
when
  SensorState(sensorName=="TIME_DAY_NAME_IN_WEEK", $e:value)
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_ARRIVAL."+$e), $va:value)
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_DEPARTURE."+$e), $vd: value)
then
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL", $va.toString());
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE", $vd.toString());
end

rule "-PSB: reset ACTUAL_TIME_ARRIVAL"
when
  SensorState(sensorName=="NEXT_EVENT", value=="Arrive")
then
  commands.execute("ACTUAL_TIME_ARRIVAL","-");
end

rule "-PSB: reset ACTUAL_TIME_DEPARTURE"
when
  SensorState(sensorName=="ACTUAL_TIME_ARRIVAL",value=="-")
then
  commands.execute("ACTUAL_TIME_DEPARTURE","-");
end

rule "PSB: decrease vacation counter at midnight"
when
  $timer: SensorState(sensorName=="TIME_HH:MM:SS", value!="N/A", eval(value.toString().substring(0,5).equals("00:00"))) // more reliable than timer(cron: )
  SensorState(sensorName=="VACATION_DAYS", $v: value, eval(Integer.parseInt(value.toString())>0), this before [2m] $timer)
then
  commands.execute("VACATION_DAYS", Integer.parseInt($v.toString())-1);
end

rule "PSB: reset action at midnight"
when
  SensorState(sensorName=="TIME_HH:MM:SS", value!="N/A", eval(value.toString().substring(0,5).equals("00:00"))) // more reliable than timer(cron: )
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", "-");
  commands.execute("NEXT_EVENT", "-");
end

rule "-PSB: Move ETD to ET at arrive init"
// This one is needed for cases when system is restart after arrive time
when
  SensorState(sensorName=="TIME_DAY_NAME_IN_WEEK",$e:value)
  SensorState(sensorName=="TIME_HH:MM:SS",$h:value)
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_ARRIVAL."+$e), eval(util.parseTimestamp(value) <= util.parseTimestamp($h)), eval(value.toString().length()==5))
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_DEPARTURE."+$e), $vd:value, eval(value.toString().length()==5))
//  SensorState(sensorName=="NEXT_EVENT", value=="-")
  SensorState(sensorName=="LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", value == "--:--")
then
   commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $vd.toString());
   commands.execute("UI_ESTIMATED_TIME_DEPARTURE", $vd.toString());
   commands.execute("NEXT_EVENT", "Departure");
end

rule "-PSB: Move ETD to ET at arrive"
when
  SensorState(sensorName=="TIME_DAY_NAME_IN_WEEK",$e:value)
  SensorState(sensorName=="TIME_HH:MM:SS",$h:value)
  SensorState(sensorName=="NEXT_EVENT", value=="Arrive")
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_DEPARTURE."+$e), $vd:value)
  SensorState(sensorName=="UI_ESTIMATED_TIME_ARRIVAL", value != "-", value != "--:--", value != "status")
  SensorState(sensorName=="UI_ESTIMATED_TIME_ARRIVAL", eval(util.parseTimestamp(value) < util.parseTimestamp($h)))
  SensorState(sensorName=="VACATION_DAYS", eval(Integer.parseInt(value.toString())==0))
then
   commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $vd.toString());
   commands.execute("NEXT_EVENT", "Departure");
end

rule "PSB: actual arrival time earlier when temperature increased and person detected"
timer(int: 10s) // Prevent glitch at midnight reset
when
  // Before attendance schedule
  SensorState(sensorName=="TIME_HH:MM:SS",$h:value)
  SensorState(sensorName=="NEXT_EVENT", value=="Arrive")
  // Temperature increased manually (higher than ECO)
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $vc: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", eval(util.parseDouble(value) > java.lang.Math.max(util.parseDouble($vc)-5.0, 16.0)))
  // Person detected
  SensorState(sensorName=="PRESENCE_AS_INTEGER", value == "1")
  SensorState(sensorName=="ACTUAL_TIME_ARRIVAL",value=="-")
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", $h.toString().substring(0,5));
end

rule "PSB: fetch actual arrival time"
when
  SensorState(sensorName=="TIME_HH:MM:SS", $h:value)
  SensorState(sensorName=="ACTUAL_TIME_ARRIVAL", value == "-")
  SensorState(sensorName=="NEXT_EVENT", value=="Departure")
  SensorState(sensorName=="PRESENCE_AS_INTEGER", value=="1")
then
  commands.execute("ACTUAL_TIME_ARRIVAL", $h.toString().substring(0,5));
end

rule "PSB: fetch earlier actual arrival time up to 30 min v02"
when
  SensorState(sensorName=="TIME_HH:MM:SS", $h:value, eval(util.parseTimestamp(value) >= util.parseTimestamp("04:30"))) // Earliest time of arrival is 4:30 AM
  SensorState(sensorName=="ACTUAL_TIME_ARRIVAL", value == "-")
  SensorState(sensorName=="NEXT_EVENT", value=="Arrive")
  SensorState(sensorName=="PRESENCE_AS_INTEGER", value=="1")
  SensorState(sensorName=="UI_ESTIMATED_TIME_ARRIVAL", value != "-", value != "--:--")
  SensorState(sensorName=="UI_ESTIMATED_TIME_ARRIVAL", eval(util.parseTimestamp(util.shiftTime(value,-30)) <= util.parseTimestamp($h)))
then
  commands.execute("ACTUAL_TIME_ARRIVAL", $h.toString().substring(0,5));
end

rule "PSB: Move - to ET at end of work"
timer(int: 1s) // avoid racing
when
  SensorState(sensorName=="TIME_HH:MM:SS",$h:value)
  SensorState(sensorName=="UI_ESTIMATED_TIME_DEPARTURE", value != "-", value != "--:--")
  SensorState(sensorName=="UI_ESTIMATED_TIME_DEPARTURE", eval(util.parseTimestamp(value) < util.parseTimestamp($h)))
  SensorState(sensorName=="NEXT_EVENT", value=="Departure")
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", "-");
  commands.execute("NEXT_EVENT", "-");
end

rule "PSB: Move - to ET on vacation"
when
  SensorState(sensorName=="VACATION_DAYS", eval(Integer.parseInt(value.toString())>0))
then
  commands.execute("LEGACY_UI_ESTIMATED_TIME_ARRIVAL_DEPARTURE", "-");
  commands.execute("NEXT_EVENT", "-");
end

rule "PSB: fetch actual departure time"
when
  SensorState(sensorName=="ACTUAL_TIME_ARRIVAL", value != "-")
  SensorState(sensorName=="ACTUAL_TIME_DEPARTURE", value == "-")
  SensorState(sensorName=="NEXT_EVENT", value=="-")
  SensorState(sensorName=="PRESENCE_LAST_DETECTED_TIME", $v:value, eval(value.toString().length()>4))
then
  commands.execute("ACTUAL_TIME_DEPARTURE", $v.toString().substring(0,5));
  commands.execute("PRESENCE_LAST_DETECTED_TIME","-");
end

rule "PSB: fetch later departure time"
when
  SensorState(sensorName=="TIME_DAY_NAME_IN_WEEK",$e:value)
  SensorState(sensorName=="NEXT_EVENT", value=="-")
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_DEPARTURE."+$e), $vd:value)
  SensorState(sensorName=="ACTUAL_TIME_ARRIVAL", value != "-")
  SensorState(sensorName=="ACTUAL_TIME_DEPARTURE", value != "-")
  SensorState(sensorName=="PRESENCE_LAST_DETECTED_TIME", $v:value, eval(value.toString().length()>4),
                                              eval(util.parseTimestamp(value)<=util.parseTimestamp(util.shiftTime($vd,15))), // Till 15 min after scheduled departure
                                              eval(util.parseTimestamp(value)<=util.parseTimestamp("23:55"))) 	      	 // Till 23:55 - does	not wrap on midnight
  SensorState(sensorName=="VACATION_DAYS", eval(Integer.parseInt(value.toString())==0))
then
  commands.execute("ACTUAL_TIME_DEPARTURE", $v.toString().substring(0,5));
  commands.execute("PRESENCE_LAST_DETECTED_TIME","-");
end

rule "PSB: adjust estimated times at midnight"
when
  SensorState(sensorName=="TIME_DAY_NAME_IN_WEEK", $e: value)
  $timer: SensorState(sensorName=="TIME_HH:MM:SS", value!="N/A", eval(value.toString().substring(0,5).equals("23:58"))) // more reliable than timer(cron: )
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_DEPARTURE."+$e), $ved:value, this before [1m] $timer) // Loop cut
  SensorState(sensorName matches ("UI_ESTIMATED_TIME_ARRIVAL."+$e), $vea:value, this before [1m] $timer)
  SensorState(sensorName=="ACTUAL_TIME_DEPARTURE", $vd:value, value!="-")
  SensorState(sensorName=="ACTUAL_TIME_ARRIVAL", $va:value, value!="-")
  SensorState(sensorName=="VACATION_DAYS", eval(Integer.parseInt(value.toString())==0))
then
  Double alpha = 2.0/(3+1); // 3 stays for 3 days exponential average
  long nt = (long) (alpha*util.parseTimestamp($va) + (1-alpha)*util.parseTimestamp($vea));
  commands.execute("UI_ESTIMATED_TIME_ARRIVAL."+$e.toString(), util.formatTimestamp(nt));
  LOG.fine("EA="+$vea.toString()+" AA="+$va.toString()+" NA="+ util.formatTimestamp(nt));
  nt = (long) (alpha*util.parseTimestamp($vd) + (1-alpha)*util.parseTimestamp($ved));
  commands.execute("UI_ESTIMATED_TIME_DEPARTURE."+$e.toString(), util.formatTimestamp(nt));
  LOG.fine("ED="+$ved.toString()+" AD="+$vd.toString()+" ND="+ util.formatTimestamp(nt));
end

rule "--PSB: move sense"
when
  SensorState($s:sensorName=="SENSOR_PRESENCE", value=="on")
  SensorState(sensorName=="TIME_HH:MM:SS", $h:value)
then
  LOG.info("Move sense on "+$s+" @"+$h);
  commands.execute("PRESENCE_LAST_DETECTED_TIME", $h.toString());
end

rule "--pir echo"
when
  SensorState(sensorName=="SENSOR_PRESENCE", $v:value)
  SensorState(sensorName=="TIME_HH:MM:SS", $h:value)
then
  LOG.info("PIR state "+$v.toString()+" @"+$h);
end

rule "-PSB: person sense"
when
  SensorState($s:sensorName=="SENSOR_PRESENCE", value=="on")
  SensorState(sensorName=="PRESENCE_AS_INTEGER", value!="1")
then
  commands.execute("PRESENCE_AS_INTEGER", "1");
end

rule "-PSB: no person sense"
timer(int: 2s)
when
  SensorState(sensorName=="SENSOR_PRESENCE", value!="on")
  SensorState(sensorName=="PRESENCE_AS_INTEGER", value!="0")
then
  commands.execute("PRESENCE_AS_INTEGER", "0");
end

rule "-PSB: window open sense"
when
  SensorState(sensorName=="SENSOR_WINDOW", value=="on")
then
  commands.execute("WINDOW_STATE","Open");
end

rule "-PSB: window closed sense"
when
  SensorState(sensorName=="SENSOR_WINDOW", value=="off")
then
  commands.execute("WINDOW_STATE","Closed");
end

rule "--FS outside temperature sense"
when
  SensorState(sensorName=="SENSOR_OUTSIDE_TEMP", $v: value)
then
  commands.execute("UI_OUTSIDE_TEMP", $v.toString() );
  LOG.fine("Fake outside temperature: "+$v.toString() );
end

rule "--FS inside temperature sense"
when
  SensorState(sensorName=="SENSOR_INSIDE_TEMP", $v: value)
then
  LOG.fine("Fake inside temperature: "+ $v.toString() );
  commands.execute("UI_INSIDE_TEMP", $v.toString() );
end

rule "PSB: Presence"
when
  SensorState(sensorName == "PRESENCE_AS_INTEGER", value == "1")
  SensorState(sensorName=="NEXT_EVENT", value=="Departure") // within expected attendance schedule
then
  commands.execute("PRESENCE_DETECTED_LATCHED","Yes");
end

rule "PSB: Absence when 30 min no movement"
timer(int: 30m)
when
  SensorState(sensorName == "PRESENCE_AS_INTEGER", value == "0")
  SensorState(sensorName=="NEXT_EVENT", value=="Departure") // within expected attendance schedule
then
  commands.execute("PRESENCE_DETECTED_LATCHED","No");
end

rule "PSB: Absence after 15 min v02"
timer(int: 15m)
when
  SensorState(sensorName == "PRESENCE_AS_INTEGER", value == "0")
then
  commands.execute("PRESENCE_DETECTED_LATCHED","No");
end

rule "-PSB: Absence after scheduled presence time"
when
  SensorState(sensorName=="NEXT_EVENT", value!="Departure") // outsidse expected attendance schedule
then
  commands.execute("PRESENCE_DETECTED_LATCHED","No");
end

rule "-PSB: heating ECO"
when
(
  SensorState(sensorName=="NEXT_EVENT", value!="Departure") || // outsidse expected attendance schedule
  SensorState(sensorName=="HEATING_DISABLED", value=="Yes")
)
then
  commands.execute("HEATING_MODE","ECO");
end

rule "-PSB: heating Stand-by from ECO"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="NEXT_EVENT", value=="Departure") // within expected attendance schedule
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
  SensorState(sensorName=="HEATING_MODE", value == "ECO")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $vc: value)
then
  commands.execute("CURRENT_COMFORT_TARGET_TEMP", $vc.toString());
  commands.execute("HEATING_MODE", "Stand-by");
end

rule "-PSB: heating Stand-by from ECO preheating 30 min v02"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="NEXT_EVENT", value=="Arrive") // within expected attendance schedule
  SensorState(sensorName=="HEATING_MODE", value == "ECO")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $vc: value)

  SensorState(sensorName=="TIME_HH:MM:SS", $h:value, eval(util.parseTimestamp(value) >= util.parseTimestamp("04:30"))) // Earliest time of arrival is 4:30 AM
  SensorState(sensorName=="UI_ESTIMATED_TIME_ARRIVAL", value != "-", value != "--:--")
  SensorState(sensorName=="UI_ESTIMATED_TIME_ARRIVAL", eval(util.parseTimestamp(util.shiftTime(value,-30)) <= util.parseTimestamp($h)))
then
  commands.execute("CURRENT_COMFORT_TARGET_TEMP", $vc.toString());
  commands.execute("HEATING_MODE", "Stand-by");
end

rule "-PSB: heating Stand-by from Comfort"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="NEXT_EVENT", value=="Departure") // within expected attendance schedule
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
  SensorState(sensorName=="HEATING_MODE", value == "Comfort")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $vc: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", value==$vc) // Only when no manual temperature increase
then
  commands.execute("HEATING_MODE","Stand-by");
end

rule "-PSB: heating Comfort on presence"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $v: value)
then
  commands.execute("HEATING_MODE","Comfort");
  commands.execute("CURRENT_COMFORT_TARGET_TEMP", $v.toString());
end

rule "-PSB: heating Comfort on temperature increase"
timer(int: 1s) // debounce
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $vc: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", eval(util.parseDouble(value) > util.parseDouble($vc)))
  SensorState(sensorName=="HEATING_MODE", value != "Comfort")
then
  commands.execute("HEATING_MODE","Comfort");
end

rule "-PSB: heating setpoint ECO"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="HEATING_MODE", value=="ECO")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $v: value)
then
  String s = $v.toString();
  Double t;
  try{
    t = java.lang.Math.max(16.0, Double.parseDouble(s.substring(0,s.length()-1))-5); // 5 degrees below comfort
  } catch (NumberFormatException e){
    t = 16.0;
  }
  commands.execute("ACTUATOR_TARGET_TEMP", String.format("%.1f",t));
  commands.execute("CURRENT_COMFORT_TARGET_TEMP", String.format("%.1f\u00B0",t));
end

rule "-PSB: heating setpoint ECO summer"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="Yes")
  SensorState(sensorName=="HEATING_MODE", value=="ECO")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $v: value)
then
  String s = $v.toString();
  Double t = java.lang.Math.max(16.0, Double.parseDouble(s.substring(0,s.length()-1))-5); // 5 degrees below comfort
  commands.execute("ACTUATOR_TARGET_TEMP", String.format("%.1f",t));
  commands.execute("CURRENT_COMFORT_TARGET_TEMP", "-");
end

rule "-PSB: heating setpoint Stand-by"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="HEATING_MODE", value=="Stand-by")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $v: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", value==$v) // When temperature changed manually keep it till ECO
then
  String s = $v.toString();
  Double t = java.lang.Math.max(16.0, Double.parseDouble(s.substring(0,s.length()-1))-1); // 1 degree below comfort
  commands.execute("ACTUATOR_TARGET_TEMP", String.format("%.1f",t));
  commands.execute("CURRENT_COMFORT_TARGET_TEMP", s); // But the user is not aware as on display there is comfort
end

rule "-PSB: heating setpoint Comfort"
timer(int: 1s) // avoid race between "HEATING_MODE" & "CURRENT_COMFORT_TARGET_TEMP"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="HEATING_MODE", value=="Comfort")
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", $v: value) // set by rule "PSB: heating Comfort" to SETTINGS_COMFORT_TARGET_TEMP or manually
then
  String s = $v.toString();
  Double t = java.lang.Math.max(16.0, Double.parseDouble(s.substring(0,s.length()-1)));
  commands.execute("ACTUATOR_TARGET_TEMP", String.format("%.1f",t));
end

rule "-PSB: energy efficiency 1"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 23)) // Comfort+
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "0.0");
  commands.execute("UI_ECO_SCORE", 0);
end

rule "-PSB: energy efficiency 2"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 23)) // Comfort+
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "0.5");
  commands.execute("UI_ECO_SCORE", 0);
end

// v02
rule "-PSB: energy efficiency 2-1 v02"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) < 23)) // Comfort, Comfort-, Comfort--
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
  SensorState(sensorName=="UI_OUTSIDE_TEMP", $t: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", eval(util.parseDouble($t) < util.parseDouble(value))) // Lower outside temperature
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "0.5");
  commands.execute("UI_ECO_SCORE", 0);
end

rule "-PSB: energy efficiency 2-2 v02"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Closed")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 23)) // Comfort+
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "0.5");
  commands.execute("UI_ECO_SCORE", 0);
end

rule "-PSB: energy efficiency 2-3 v02"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Closed")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) < 23), eval(Double.parseDouble(value.toString()) >= 18)) // Comfort, Comfort-, Comfort--, not eco
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.0");
  commands.execute("UI_ECO_SCORE", 0);
end
// v02

rule "-PSB: energy efficiency 3"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 21), eval(Double.parseDouble(value.toString()) < 23)) // Comfort
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.0");
  commands.execute("UI_ECO_SCORE", 0);
end

rule "-PSB: energy efficiency 4"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Open") // Added because otherwise it overrules efficiency 11
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 21), eval(Double.parseDouble(value.toString()) < 23)) // Comfort
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.0");
  commands.execute("UI_ECO_SCORE", 0);
end

rule "-PSB: energy efficiency 5"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="HEATING_MODE", value=="Stand-by")
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.0");
  commands.execute("UI_ECO_SCORE", 0);
end

rule "-PSB: energy efficiency 6"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 23)) // Comfort+
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.0");
  commands.execute("UI_ECO_SCORE", 0);
end

rule "-PSB: energy efficiency 7"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
  SensorState(sensorName=="HEATING_MODE", value=="Stand-by")
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
  SensorState(sensorName=="UI_OUTSIDE_TEMP", $t: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", eval(util.parseDouble($t) < util.parseDouble(value))) // Lower outside temperature
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.5");
  commands.execute("UI_ECO_SCORE", 1);
end

rule "-PSB: energy efficiency 8"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
  SensorState(sensorName=="HEATING_MODE", value=="ECO")
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
  SensorState(sensorName=="UI_OUTSIDE_TEMP", $t: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", eval(util.parseDouble($t) < util.parseDouble(value))) // Lower outside temperature
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.5");
  commands.execute("UI_ECO_SCORE", 1);
end

rule "-PSB: energy efficiency 9"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Closed")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 23)) // Comfort+
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.5");
  commands.execute("UI_ECO_SCORE", 1);
end

rule "-PSB: energy efficiency 10"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 20), eval(Double.parseDouble(value.toString()) < 21)) // Comfort-
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
  SensorState(sensorName=="UI_OUTSIDE_TEMP", $t: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", eval(util.parseDouble($t) < util.parseDouble(value))) // Lower outside temperature
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "1.5");
  commands.execute("UI_ECO_SCORE", 1);
end

rule "-PSB: energy efficiency 11"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Closed")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 21), eval(Double.parseDouble(value.toString()) < 23)) // Comfort
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "2.0");
  commands.execute("UI_ECO_SCORE", 2);
end

rule "-PSB: energy efficiency 12 v02"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Closed")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) >= 20), eval(Double.parseDouble(value.toString()) < 21)) // Comfort-
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes") // v02
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "2.5");
  commands.execute("UI_ECO_SCORE", 3);
end

rule "-PSB: energy efficiency 13"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) < 20)) // Comfort--
  SensorState(sensorName=="HEATING_MODE", value!="ECO")  // needed because of race
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes")
  SensorState(sensorName=="UI_OUTSIDE_TEMP", $t: value)
  SensorState(sensorName=="CURRENT_COMFORT_TARGET_TEMP", eval(util.parseDouble($t) >= util.parseDouble(value))) // Higher outside temperature
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "3.0");
  commands.execute("UI_ECO_SCORE", 4);
end

rule "-PSB: energy efficiency 14"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Closed")
  SensorState(sensorName=="HEATING_MODE", value=="ECO")
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="No")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "3.0");
  commands.execute("UI_ECO_SCORE", 4);
end

rule "-PSB: energy efficiency 15"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="WINDOW_STATE", value=="Closed")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", eval(Double.parseDouble(value.toString()) < 20)) // Comfort--
  SensorState(sensorName=="PRESENCE_DETECTED_LATCHED", value=="Yes") // No important IMHO
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "3.0");
  commands.execute("UI_ECO_SCORE", 4);
end

rule "-PSB: energy efficiency Summer"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="Yes")
then
  commands.execute("LEGACY_UI_ECO_SCORE_IMAGE", "3.0");
  commands.execute("UI_ECO_SCORE", 4);
end

rule "--PSB: increase total score every 15m"
when
  $timer: SensorState(sensorName=="TIME_HH:MM:SS", value!="N/A", eval(Integer.parseInt(value.toString().substring(3,5)) % 15 == 0)) // more reliable than timer(cron: )
  SensorState(sensorName=="UI_ECO_SCORE", $s: value)
  SensorState(sensorName=="LEGACY_UI_ECO_SCORE_CUMULATIVE", $ts: value, this before [1m] $timer)
then
  commands.execute("LEGACY_UI_ECO_SCORE_CUMULATIVE", Integer.parseInt($ts.toString())+Integer.parseInt($s.toString()));
end

rule "PSB: reward"
when
  $ts: SensorState(sensorName=="LEGACY_UI_ECO_SCORE_CUMULATIVE", $s: value, eval(Integer.parseInt(value.toString()) >= 1000))
  SensorState(sensorName=="LEGACY_UI_ECO_SCORE_CUMULATIVE_SLIDER", $l: value, this before [1m] $ts)
then
  Integer i = Integer.parseInt($s.toString());
  commands.execute("LEGACY_UI_ECO_SCORE_CUMULATIVE", i-1000); // Reset score
  commands.execute("LEGACY_UI_ECO_SCORE_CUMULATIVE_SLIDER", Integer.parseInt($l.toString())+1);
end

rule "--PSB: display totalscore"
when
  SensorState(sensorName=="LEGACY_UI_ECO_SCORE_CUMULATIVE", $ts: value)
then
   commands.execute("LEGACY_UI_ECO_SCORE_CUMULATIVEdisp", $ts+" / 1000");
end

rule "PSB: summer"
timer(int: 1h)
when
//  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $sp: value)
//  SensorState(sensorName=="UI_OUTSIDE_TEMP", value!="", eval(util.parseDouble($sp) <= util.parseDouble(value) )) // Outside temp higher than set point
  SensorState(sensorName=="UI_OUTSIDE_TEMP", $o:value) // Only for logging
  SensorState(sensorName=="YT.summer", value=="0") // Y-con test
  SensorState(sensorName=="HEATING_DISABLED", value!="Yes")
then
  LOG.fine("Summer is ON; outside="+$o.toString());
  commands.execute("HEATING_DISABLED", "Yes");
end

rule "PSB: no summer"
timer(int: 1h)
when
//  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", $sp: value)
//  SensorState(sensorName=="UI_OUTSIDE_TEMP", value!="", eval(util.parseDouble($sp) > util.parseDouble(value) )) // Outside temp lower than set point
  SensorState(sensorName=="UI_OUTSIDE_TEMP", $o:value) // Only for logging
  SensorState(sensorName=="YT.summer", value=="1") // Y-con test
  SensorState(sensorName=="HEATING_DISABLED", value!="No")
then
  LOG.fine("Summer is OFF; outside="+$o.toString());
  commands.execute("HEATING_DISABLED", "No");
end

rule "-PSB: advice 1"
when
  SensorState(sensorName=="WINDOW_STATE", value=="Open")
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", $sp: value)
  SensorState(sensorName=="UI_OUTSIDE_TEMP", value!="", eval(Double.parseDouble($sp.toString()) > util.parseDouble(value) )) // Outside temp lower than set point
then
  commands.execute("LEGACY_UI_ADVICE_TEXT", "It's more energy efficient to close the windows when it is colder outside than it is inside");
  commands.execute("LEGACY_UI_ADVICE_SHOWN", "OFF");
  insert(new AdviceGiven("It's more energy efficient to close the windows when it is colder outside than it is inside"));
end

rule "-PSB: advice 1 done"
when
  SensorState(sensorName=="ACTUATOR_TARGET_TEMP", $sp: value)
(
  SensorState(sensorName=="WINDOW_STATE", value=="Closed") ||
  SensorState(sensorName=="UI_OUTSIDE_TEMP", value!="", eval(Double.parseDouble($sp.toString()) <= util.parseDouble(value) )) // Outside temp lower than set point
)
  SensorState(sensorName=="LEGACY_UI_ADVICE_TEXT",eval(value.toString().substring(0,9).equals("It's more")))
then
  commands.execute("LEGACY_UI_ADVICE_TEXT", "You're doing great!");
  commands.execute("LEGACY_UI_ADVICE_SHOWN", "OFF");
end

rule "-PSB: advice 2"
when
  SensorState(sensorName=="HEATING_DISABLED", value=="No")
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", eval(util.parseDouble(value) > 20.5)) // Average is 20 hardcoded or from sensor?
then
  commands.execute("LEGACY_UI_ADVICE_TEXT", "Your comfort temperature is set higher than average. You can adjust it on the settings page.");
  commands.execute("LEGACY_UI_ADVICE_SHOWN", "OFF");
  insert(new AdviceGiven("Your comfort temperature is set higher than average. You can adjust it on the settings page."));
end

rule "-PSB: advice 2 done"
when
  SensorState(sensorName=="SETTINGS_COMFORT_TARGET_TEMP", eval(util.parseDouble(value) <= 20.5)) // Average is 20 hardcoded or from sensor?
  SensorState(sensorName=="LEGACY_UI_ADVICE_TEXT",eval(value.toString().substring(0,12).equals("Your comfort")))
then
  commands.execute("LEGACY_UI_ADVICE_TEXT", "You're doing great!");
  commands.execute("LEGACY_UI_ADVICE_SHOWN", "OFF");
end

rule "-PSB: advice 3"
when
// irregular attendence
then
  commands.execute("LEGACY_UI_ADVICE_SHOWN", "OFF");
end

rule "-PSB: advice 4"
when
(
  SensorState(sensorName=="LEGACY_UI_ADVICE_SHOWN", value=="ON") ||
  SensorState(sensorName=="HEATING_DISABLED", value=="Yes")
)
then
  commands.execute("LEGACY_UI_ADVICE_TEXT", "You're doing great!");
  commands.execute("LEGACY_UI_ADVICE_SHOWN", "OFF");
  insert(new AdviceGiven("You're doing great!"));
end

declare AdviceGiven
  @role(event)
  @expires(10m)
  advice : String
end

rule "-PSB: advices given counter"
when
  SensorState(sensorName=="LEGACY_UI_ADVICE_TEXT", value!="", value!="You're doing great!")
  //AdviceGiven(advice!="You're doing great!")  // This one fires with the same advice
then
  int cnt = 0;
  try{
    cnt = Integer.parseInt(persistence.readData("LEGACY_UI_ADVICE_TEXTGIVEN_0","0"));
  }finally{
    cnt += 1;
    persistence.writeData("LEGACY_UI_ADVICE_TEXTGIVEN_0", cnt);
  }
end

rule "-PSB: vacation inc"
  timer(int:300ms)
when
  SensorState(sensorName=="VACATION_DAYS", $v: value)
  SensorState(sensorName=="VACATION_DAYS.inc", value=="ON")
then
  commands.execute("VACATION_DAYS", Integer.parseInt($v.toString())+1);
  commands.execute("VACATION_DAYS.inc", "OFF");
end

rule "-PSB: vacation dec"
  timer(int:300ms)
when
  SensorState(sensorName=="VACATION_DAYS", $v: value, eval(Integer.parseInt(value.toString()) > 0))
  SensorState(sensorName=="VACATION_DAYS.dec", value=="ON")
then
  commands.execute("VACATION_DAYS", Integer.parseInt($v.toString())-1);
  commands.execute("VACATION_DAYS.dec", "OFF");
end

rule "-PSB: vacation inc/dec" // needed so the ON value does not hang
  salience -10
  timer(int:300ms)
when
  SensorState(sensorName matches "VACATION_DAYS...c", $s: sensorName, value=="ON")
then
  commands.execute($s, "OFF");
end

rule "PSB: start next week stats"
  timer(cron: 0 0 0 ? * 1) // Every Sunday morning at midnight
when
  // Time scheduled
  Number($arrive: longValue>0) from accumulate(SensorState(sensorName matches "UI_ESTIMATED_TIME_ARRIVAL.*", $a:value), sum(util.parseTimestamp($a)))
  Number($departure: longValue>0) from accumulate(SensorState(sensorName matches "UI_ESTIMATED_TIME_DEPARTURE.*", $d:value), sum(util.parseTimestamp($d)))
then
  persistence.writeData("MANUAL_SET_TEMP_COUNT_PER_WEEK_4" ,persistence.readData("MANUAL_SET_TEMP_COUNT_PER_WEEK_3","0"));
  persistence.writeData("MANUAL_SET_TEMP_COUNT_PER_WEEK_3" ,persistence.readData("MANUAL_SET_TEMP_COUNT_PER_WEEK_2","0"));
  persistence.writeData("MANUAL_SET_TEMP_COUNT_PER_WEEK_2" ,persistence.readData("MANUAL_SET_TEMP_COUNT_PER_WEEK_1","0"));
  persistence.writeData("MANUAL_SET_TEMP_COUNT_PER_WEEK_1" ,persistence.readData("MANUAL_SET_TEMP_COUNT_PER_WEEK_0","0"));
  persistence.writeData("MANUAL_SET_TEMP_COUNT_PER_WEEK_0" , "0");

  persistence.writeData("MANUAL_SCHEDULE_CHANGE_COUNT_4" ,persistence.readData("MANUAL_SCHEDULE_CHANGE_COUNT_3","0"));
  persistence.writeData("MANUAL_SCHEDULE_CHANGE_COUNT_3" ,persistence.readData("MANUAL_SCHEDULE_CHANGE_COUNT_2","0"));
  persistence.writeData("MANUAL_SCHEDULE_CHANGE_COUNT_2" ,persistence.readData("MANUAL_SCHEDULE_CHANGE_COUNT_1","0"));
  persistence.writeData("MANUAL_SCHEDULE_CHANGE_COUNT_1" ,persistence.readData("MANUAL_SCHEDULE_CHANGE_COUNT_0","0"));
  persistence.writeData("MANUAL_SCHEDULE_CHANGE_COUNT_0" , "0");

  persistence.writeData("LEGACY_UI_ADVICE_TEXTGIVEN_4" ,persistence.readData("LEGACY_UI_ADVICE_TEXTGIVEN_3","0"));
  persistence.writeData("LEGACY_UI_ADVICE_TEXTGIVEN_3" ,persistence.readData("LEGACY_UI_ADVICE_TEXTGIVEN_2","0"));
  persistence.writeData("LEGACY_UI_ADVICE_TEXTGIVEN_2" ,persistence.readData("LEGACY_UI_ADVICE_TEXTGIVEN_1","0"));
  persistence.writeData("LEGACY_UI_ADVICE_TEXTGIVEN_1" ,persistence.readData("LEGACY_UI_ADVICE_TEXTGIVEN_0","0"));
  persistence.writeData("LEGACY_UI_ADVICE_TEXTGIVEN_0" , "0");

  // Time scheduled
  long minutes = ($departure-$arrive)/60000;
  long hours = minutes/60;

  persistence.writeData("PRESENCE_HOURS_CUMULATIVE_WEEK_4" ,persistence.readData("PRESENCE_HOURS_CUMULATIVE_WEEK_3","0:00"));
  persistence.writeData("PRESENCE_HOURS_CUMULATIVE_WEEK_3" ,persistence.readData("PRESENCE_HOURS_CUMULATIVE_WEEK_2","0:00"));
  persistence.writeData("PRESENCE_HOURS_CUMULATIVE_WEEK_2" ,persistence.readData("PRESENCE_HOURS_CUMULATIVE_WEEK_1","0:00"));
  persistence.writeData("PRESENCE_HOURS_CUMULATIVE_WEEK_1" , String.format("%2d:%02d", hours, minutes%60));
end

// Fake sensors start

rule "-Fake sensors init"
then
  commands.execute("SENSOR_OUTSIDE_TEMP", "15\u00B0");
  commands.execute("SENSOR_INSIDE_TEMP", "19.5\u00B0");
  commands.execute("SENSOR_PRESENCE", "off");
  commands.execute("SENSOR_WINDOW", "off");
end

rule "--Fake sensors Toutside inc"
  timer(int:300ms)
when
  SensorState(sensorName == "SENSOR_OUTSIDE_TEMP", $v: value, eval(util.parseDouble(value) < 50))
  SensorState(sensorName == "SENSOR_OUTSIDE_TEMP.inc" , value == "on")
then
  commands.execute("SENSOR_OUTSIDE_TEMP.inc","off");
  commands.execute("SENSOR_OUTSIDE_TEMP", util.shiftDouble($v.toString(), 0.1, "\u00B0"));
end

rule "--Fake sensors Toutside dec"
  timer(int:300ms)
when
  SensorState(sensorName == "SENSOR_OUTSIDE_TEMP", $v: value, eval(util.parseDouble(value) > -40))
  SensorState(sensorName == "SENSOR_OUTSIDE_TEMP.dec" , value == "on")
then
  commands.execute("SENSOR_OUTSIDE_TEMP.dec","off");
  commands.execute("SENSOR_OUTSIDE_TEMP", util.shiftDouble($v.toString(), -0.1, "\u00B0"));
end

rule "--Fake sensors Tinside inc"
  timer(int:300ms)
when
  SensorState(sensorName == "SENSOR_INSIDE_TEMP", $v: value, eval(util.parseDouble(value) < 40))
  SensorState(sensorName == "SENSOR_INSIDE_TEMP.inc" , value == "on")
then
  commands.execute("SENSOR_INSIDE_TEMP.inc","off");
  commands.execute("SENSOR_INSIDE_TEMP", util.shiftDouble($v.toString(), 0.1, "\u00B0"));
end

rule "--Fake sensors Tinside dec"
  timer(int:300ms)
when
  SensorState(sensorName == "SENSOR_INSIDE_TEMP", $v: value, eval(util.parseDouble(value) > 0))
  SensorState(sensorName == "SENSOR_INSIDE_TEMP.dec" , value == "on")
then
  commands.execute("SENSOR_INSIDE_TEMP.dec","off");
  commands.execute("SENSOR_INSIDE_TEMP", util.shiftDouble($v.toString(), -0.1, "\u00B0"));
end

rule "--Fake sensors PIR off"
  timer(int: 2s)
when
  SensorState(sensorName=="SENSOR_PRESENCE", value=="on")
then
  commands.execute("SENSOR_PRESENCE", "off");
end

// Fake sensors end