FROM openremote/controller:latest

RUN rm -r /opt/or-resources/*

ENV rules_data=/opt/or-resources/data/
ADD config/env.drl /opt/or-resources/rules/env.drl
ADD config/GVconfig.txt /opt/or-resources/data/GVconfig.txt

ADD webconsole.war /opt/OpenRemote-Controller/webapps/

ADD config/controller.xml /opt/or-resources/controller.xml

USER root
# nc is a great connectivity debug tool
RUN apt-get update && apt-get -y install netcat
RUN chown -R openremote.openremote /opt/or-resources
USER openremote

CMD ["run"]
