# OpenRemote v3
#
# Profile for doing UI development work.
#
# Please see profile/deploy.yml for configuration details for each service.
#
version: '2.4'

volumes:
  temp-data:

services:

  keycloak:
    extends:
      file: deploy.yml
      service: keycloak
    volumes:
      # Map custom themes
      #- ../deployment:/deployment
      - ./disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    # Access directly if needed on localhost
    ports:
      - "8081:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      # Use manager dev mode reverse proxy to access keycloak so manager and keycloak hosts match
      KEYCLOAK_FRONTEND_URL: http://${OR_HOSTNAME:-localhost}:8080/auth

  postgresql:
    extends:
      file: deploy.yml
      service: postgresql
    volumes:
      - temp-data:/tmp
    # Access directly if needed on localhost
    ports:
      - "5432:5432"

  manager:
    extends:
      file: deploy.yml
      service: manager
    image: openremote/manager:${MANAGER_VERSION:-develop}
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - temp-data:/tmp
    environment:
      OR_SETUP_RUN_ON_RESTART: ${OR_SETUP_RUN_ON_RESTART:-true}
      OR_DEV_MODE: ${OR_DEV_MODE:-true}
      KEYCLOAK_FRONTEND_URL:
    ports:
      - "8080:8080"