version: '2.4'

volumes:
  proxy-data:
  postgresql-data:
  manager-data:

services:
  proxy:
    image: openremote/proxy:latest
    restart: always
    depends_on:
      manager:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    volumes:
      - proxy-data:/deployment

  postgresql:
    image: openremote/postgresql:latest
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - manager-data:/storage

  keycloak:
    image: openremote/keycloak:latest
    restart: always
    depends_on:
      postgresql:
        condition: service_started
    environment:
      - KC_HOSTNAME=
      - KC_HOSTNAME_STRICT=false

  manager:
    image: manager
    build:
        context: .
    restart: always
    depends_on:
      keycloak:
        condition: service_started
    volumes:
      - manager-data:/storage
    environment:
      BALENA: 1
      OR_MAIN_THREAD_WAIT_MS: ${OR_MAIN_THREAD_WAIT_MS:-120000}
      OR_SETUP_TYPE: gateway
