volumes:
  proxy-data:
  postgresql-data:
  manager-data:

services:
  proxy:
    image: openremote/proxy:latest
    restart: always
    depends_on:
      manager:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    volumes:
      - proxy-data:/deployment
    env_file:
      - env

  postgresql:
    image: openremote/postgresql:latest
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - manager-data:/storage
    env_file:
      - env

  keycloak:
    image: openremote/keycloak:latest
    restart: always
    depends_on:
      postgresql:
        condition: service_started
    env_file:
      - env

  manager:
    image: openremote-manager
    build:
      context: manager-build
    restart: always
    depends_on:
      keycloak:
        condition: service_started
      postgresql:
        condition: service_started
    ports:
      - "1883:1883"
    volumes:
      - manager-data:/storage
    env_file:
      - env
