import { ControlProps, JsonFormsRendererRegistryEntry, OwnPropsOfJsonFormsRenderer, RankedTester, Tester } from "@jsonforms/core";
import { TemplateResult } from "lit";
import "@openremote/or-mwc-components/or-mwc-input";
import { JsonFormsStateContext } from "./index";
import "./layouts/layout-vertical-element";
import "./controls/control-input-element";
import "./controls/control-array-element";
import { AdditionalProps } from "./base-element";
export declare const isEnumArray: Tester;
export declare const verticalOrGroupLayoutTester: RankedTester;
export declare const verticalLayoutRenderer: (state: JsonFormsStateContext, props: OwnPropsOfJsonFormsRenderer & AdditionalProps) => TemplateResult;
export declare const constTester: RankedTester;
export declare const constRenderer: (state: JsonFormsStateContext, props: OwnPropsOfJsonFormsRenderer) => undefined;
export declare const inputControlTester: RankedTester;
export declare const inputControlRenderer: (state: JsonFormsStateContext, props: ControlProps) => TemplateResult;
export declare const objectControlTester: RankedTester;
export declare const objectControlRenderer: (state: JsonFormsStateContext, props: ControlProps & AdditionalProps) => TemplateResult | undefined;
export declare const anyOfOneOfControlTester: RankedTester;
export declare const anyOfOneOfControlRenderer: (state: JsonFormsStateContext, props: ControlProps & AdditionalProps) => TemplateResult | undefined;
export declare const allOfControlTester: RankedTester;
export declare const allOfControlRenderer: (state: JsonFormsStateContext, props: ControlProps & AdditionalProps) => TemplateResult | undefined;
export declare const arrayControlTester: RankedTester;
export declare const arrayControlRenderer: (state: JsonFormsStateContext, props: ControlProps & AdditionalProps) => TemplateResult;
export declare function getTemplateWrapper(elementTemplate: TemplateResult, deleteHandler?: () => void): TemplateResult;
export declare function unknownTemplate(): TemplateResult<1>;
export declare const StandardRenderers: JsonFormsRendererRegistryEntry[];
