apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "manager.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumeSize }}
  volumeName: manager-data-pv
  storageClassName: manual
