# ----------------------------------------------------------------------------------------
# Docker image for populating deployment-data volume with project specific customisations
# ----------------------------------------------------------------------------------------
FROM alpine:latest

ADD image /deployment
