apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: or-postgresql-cluster
spec:
  teamId: "or"
  volume:
    size: 1Gi
  numberOfInstances: 2

  preparedDatabases:
    openremote:
      defaultUsers: false
      schemas:
        public:
          defaultRoles: false
        openremote:
          defaultRoles: false
        topology:
          defaultRoles: false
      extensions:
        timescaledb: openremote
        timescaledb_toolkit: openremote
        postgis: openremote
        postgis_topology: topology
  postgresql:
    version: "16"
  dockerImage: "openremote/k8s-postgresql:1.0"

