
/*
  Adds meta column to rulesets
 */

-- UPDATE GLOBAL_RULESET
ALTER TABLE GLOBAL_RULESET
    ADD COLUMN META jsonb;

-- UPDATE ASSET_RULESET
ALTER TABLE ASSET_RULESET
    ADD COLUMN META jsonb;


-- UPDATE TENANT_RULESET
ALTER TABLE TENANT_RULESET
    ADD COLUMN META jsonb;