podLabels:
  openremote.io/public-http: "true"

ingress:
  enabled: true
  className: openremote-alb
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /auth/health/ready
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
  tls: []
