package org.openremote.test.rules;

import org.openremote.model.*;
import org.openremote.model.asset.*
import org.openremote.model.value.*
import org.openremote.model.attribute.*;

global java.util.logging.Logger LOG;
global org.openremote.model.rules.Assets assets;

rule "When vacation timestamp was set, execute AWAY scene"
when
    $residence : AssetState(type == AssetType.RESIDENCE, attributeName == "vacationUntil", valueAsNumber > 0, oldValue == null)
then
    assets.dispatch(
        new AttributeEvent(
            $residence.getId(),
            "awayScene",
            AttributeExecuteStatus.REQUEST_START.asValue()
        )
    );
end