#!/bin/bash
echo "===> Building OpenRemote source"
docker run -v $(pwd):/openremote \
    $IMAGE_NAME \
    /bin/sh -c "./gradlew --console plain clean installDist" || exit 1

echo "===> Building OpenRemote images"
docker run \
  -v $(pwd):/openremote \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --env DATE_TAG=$CACHE_TAG \
  $IMAGE_NAME \
  /bin/sh -c "docker-compose -f profile/deploy.yml build --build-arg GIT_COMMIT=$SOURCE_COMMIT" || exit 1

echo "===> Pushing OpenRemote images"
docker push openremote/deployment:${CACHE_TAG:-latest}
docker push openremote/manager:${CACHE_TAG:-latest}
#docker push openremote/keycloak:${CACHE_TAG:-latest}
#docker push openremote/proxy:${CACHE_TAG:-latest}
#docker push openremote/postgresql:${CACHE_TAG:-latest}
#docker push openremote/tileserver-gl:${CACHE_TAG:-latest}
docker push openremote/manager-swarm:${CACHE_TAG:-latest}
