apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.or.httpPort }}
      protocol: TCP
      name: http
    - port: 443
      targetPort: {{ .Values.or.httpsPort }}
      protocol: TCP
      name: https
    - port: 8883
      targetPort: 8883
      protocol: TCP
      name: mqtts
    - port: 8404
      targetPort: 8404
      protocol: TCP
      name: metrics
  selector:
    {{- include "proxy.selectorLabels" . | nindent 4 }}
