apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
  {{- with .Values.service.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.or.httpPort }}
      protocol: TCP
      name: http
    - port: 443
      targetPort: {{ .Values.or.httpsPort }}
      protocol: TCP
      name: https
    - port: 8883
      targetPort: 8883
      protocol: TCP
      name: mqtts
  selector:
    {{- include "proxy.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: proxy-metrics
  {{- with .Values.service.metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.metrics.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: 8404
      protocol: TCP
  selector:
    {{- include "proxy.selectorLabels" . | nindent 4 }}
{{- end }}
