apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/xxx/Development/OpenRemote/pv/postgresql-data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
