apiVersion: v1
kind: PersistentVolume
metadata:
  name: manager-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/xxx/Development/OpenRemote/pv/manager-data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
