#!/bin/bash -e
{

# Comment out this line if you do not use Wifi
/usr/bin/wpa_passphrase 'MY_SSID' 'MY_PASSWORD' >> /etc/wpa/wpa_supplicant.conf

# TODO Test this
#if [ -f /boot/openremote-ssh.pub ]; then
#    mkdir -p /home/pi/.ssh/
#    mv /boot/openremote-ssh.pub /home/pi/.ssh/authorized_keys
#    chown -R pi:pi /home/pi/.ssh
#fi
#
#export PG_VERSION=9.6 \
#    PG_VERSION_INSTALL=9.6* \
#    POSTGIS_VERSION=2.3 \
#    GOSU_VERSION=1.10
#
#apt-get update \
#    && apt-get install -y --no-install-recommends curl vim postgresql-common \
#	&& sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf \
#	&& apt-get install -y --no-install-recommends \
#		postgresql=$PG_VERSION_INSTALL \
#		postgresql-contrib=$PG_VERSION_INSTALL \
#        postgresql-$PG_VERSION-postgis-$POSTGIS_VERSION \
#        postgresql-$PG_VERSION-postgis-$POSTGIS_VERSION-scripts \
#    && rm -rf /var/lib/apt/lists/*
#
#curl -L -o /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-arm64 \
#	&& chmod +x /usr/local/bin/gosu \
#	&& gosu nobody true
#
#export PGDATA=/var/lib/postgresql/data/
#RUN mkdir -p "$PGDATA" && chown -R postgres:postgres "$PGDATA"
#
#export PG_BIN=/usr/lib/postgresql/${PG_VERSION}/bin
#export PATH=$PATH:$PG_BIN

} > /var/log/setup.log 2>&1
