CREATE TABLE IF NOT EXISTS `controller_config` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `account_oid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__CONTROLLER_CONFIG__ACCOUNT_OID` (`account_oid` ASC) ,
  CONSTRAINT `FK__CONTROLLER_CONFIG__ACCOUNT__ACCOUNT_OID`
    FOREIGN KEY (`account_oid`)
    REFERENCES `account` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `device` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `vendor` VARCHAR(255) NULL DEFAULT NULL,
  `account_oid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__DEVICE__ACCOUNT_OID` (`account_oid` ASC) ,
  CONSTRAINT `FK__DEVICE__ACCOUNT__ACCOUNT_OID`
    FOREIGN KEY (`account_oid`)
    REFERENCES `account` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `protocol` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`oid`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `protocol_attr` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NOT NULL,
  `protocol_oid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__PROTOCOL_ATTR__PROTOCOL_OID` (`protocol_oid` ASC) ,
  CONSTRAINT `FK_PROTOCOL_ATTR__PROTOCOL__PROTOCOL_OID`
    FOREIGN KEY (`protocol_oid`)
    REFERENCES `protocol` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `device_command` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `sectionId` VARCHAR(255) NULL DEFAULT NULL,
  `device_oid` BIGINT(20) NULL DEFAULT NULL,
  `protocol_oid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__DEVICE_COMMAND__DEVICE_OID` (`device_oid` ASC) ,
  INDEX `IDX__DEVICE_COMMAND__PROTOCOL_OID` (`protocol_oid` ASC) ,
  CONSTRAINT `FK__DEVICE_COMMAND__DEVICE__DEVICE_OID`
    FOREIGN KEY (`device_oid`)
    REFERENCES `device` (`oid`),
  CONSTRAINT `FK__DEVICE_COMMAND__PROTOCOL__PROTOCOL_OID`
    FOREIGN KEY (`protocol_oid`)
    REFERENCES `protocol` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `sensor` (
  `dtype` VARCHAR(31) NOT NULL,
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  `device_oid` BIGINT(20) NULL DEFAULT NULL,
  `account_oid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__SENSOR__ACCOUNT_OID` (`account_oid` ASC) ,
  INDEX `IDX__SENSOR__DEVICE_OID` (`device_oid` ASC) ,
  CONSTRAINT `FK__SENSOR__ACCOUNT__ACCOUNT_OID`
    FOREIGN KEY (`account_oid`)
    REFERENCES `account` (`oid`),
  CONSTRAINT `FK__SENSOR__DEVICE__DEVICE_OID`
    FOREIGN KEY (`device_oid`)
    REFERENCES `device` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `state` (
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `sensor_oid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__STATE__SENSOR_OID` (`sensor_oid` ASC) ,
  CONSTRAINT `FK__STATE__SENSOR__SENSOIR_OID`
    FOREIGN KEY (`sensor_oid`)
    REFERENCES `sensor` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `range_sensor` (
  `max_value` INT(11) NULL DEFAULT NULL,
  `min_value` INT(11) NULL DEFAULT NULL,
  `oid` BIGINT(20) NOT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__RANGE_SENSOR__OID` (`oid` ASC) ,
  CONSTRAINT `FK__RANGE_SENSOR__SENSOR__OID`
    FOREIGN KEY (`oid`)
    REFERENCES `sensor` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `command_ref_item` (
  `type` VARCHAR(31) NOT NULL,
  `oid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sensor_oid` BIGINT(20) NULL DEFAULT NULL,
  `slider_oid` BIGINT(20) NULL DEFAULT NULL,
  `on_switch_oid` BIGINT(20) NULL DEFAULT NULL,
  `off_switch_oid` BIGINT(20) NULL DEFAULT NULL,
  `target_device_command_oid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`oid`) ,
  INDEX `IDX__COMMAND_REF_ITEM__SENSOR_OID` (`sensor_oid` ASC) ,
  INDEX `IDX__COMMAND_REF_ITEM__TARGET_DEVICE_COMMAND_OID` (`target_device_command_oid` ASC) ,
  INDEX `IDX__COMMAND_REF_ITEM__ON_SWITCH_OID` (`on_switch_oid` ASC) ,
  INDEX `IDX__COMMAND_REF_ITEM__OFF_SWITCH_OID` (`off_switch_oid` ASC) ,
  INDEX `IDX__COMMAND_REF_ITEM__SLIDER_OID` (`slider_oid` ASC) ,
  CONSTRAINT `FK__COMMAND_REF_ITEM__DEVICE_COMMAND__TARGET_DEVICE_COMMAND_OID`
    FOREIGN KEY (`target_device_command_oid`)
    REFERENCES `device_command` (`oid`),
  CONSTRAINT `FK__COMMAND_REF_ITEM__SENSOR__SENSOR_OID`
    FOREIGN KEY (`sensor_oid`)
    REFERENCES `sensor` (`oid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;