workspace 'GenericApp'
platform :ios, '13.0'

use_frameworks!

def shared_pods
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/Buttons'
end


target 'GenericApp' do
  project 'GenericApp'
  shared_pods
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'
end

target 'NotificationService' do
  project 'GenericApp'
  shared_pods
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
end

target 'ORLib' do
  shared_pods
  project '../ORLib/ORLib'
end
