import { AssetTypeInfo, RuleCondition } from "@openremote/model";
import { ConditionType, RulesConfig } from "../index";
import "./or-rule-asset-query";
import "./or-rule-trigger-query";
import "@openremote/or-mwc-components/or-mwc-menu";
import { ListItem } from "@openremote/or-mwc-components/or-mwc-list";
import "@openremote/or-icon";
import "@openremote/or-translate";
export declare function getWhenTypesMenu(config?: RulesConfig, assetInfos?: AssetTypeInfo[]): (ListItem | null)[];
export declare function updateRuleConditionType(ruleCondition: RuleCondition, value: string | ConditionType | undefined, config?: RulesConfig): void;
