#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $OPENREMOTE_USERNAME PASSWORD '$OPENREMOTE_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $OPENREMOTE_USERNAME;
EOSQL
