FROM postgres:9.5

ENV POSTGIS_MAJOR 2.2
ENV POSTGIS_VERSION 2.2.2+dfsg-4.pgdg80+1

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION \
           postgis=$POSTGIS_VERSION \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d

ADD 01-init-user.sh /docker-entrypoint-initdb.d/01-init-user.sh
ADD 02-init-postgis.sh /docker-entrypoint-initdb.d/02-init-postgis.sh

RUN chmod +x /docker-entrypoint-initdb.d/*.sh