apiVersion: v1
kind: PersistentVolume
metadata:
  name: manager-data-pv
{{- if .Values.aws.enabled }}
  labels:
    type: amazonEBS
{{- end }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  {{- if .Values.aws.enabled }}
  awsElasticBlockStore:
    volumeID: {{ .Values.aws.managerVolumeId }}
    fsType: ext4
  {{- else }}
  hostPath:
    path: "{{ .Values.basePath}}/manager-data"
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
