/*
 * Copyright 2017, OpenRemote Inc.
 *
 * See the CONTRIBUTORS.txt file in the distribution for a
 * full listing of individual contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.openremote.manager.server.asset;

import org.apache.camel.builder.RouteBuilder;
import org.openremote.container.Container;
import org.openremote.container.ContainerService;
import org.openremote.container.message.MessageBrokerService;
import org.openremote.container.message.MessageBrokerSetupService;
import org.openremote.container.persistence.PersistenceEvent;
import org.openremote.manager.server.agent.AgentService;
import org.openremote.manager.server.agent.ThingAttributes;
import org.openremote.manager.server.datapoint.AssetDatapointService;
import org.openremote.manager.server.rules.RulesService;
import org.openremote.model.Attribute;
import org.openremote.model.AttributeEvent;
import org.openremote.model.AttributeState;
import org.openremote.model.Attributes;
import org.openremote.model.asset.Asset;
import org.openremote.model.asset.AssetType;
import org.openremote.model.asset.ThingAttribute;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;

import static org.openremote.agent3.protocol.Protocol.SENSOR_TOPIC;
import static org.openremote.container.persistence.PersistenceEvent.PERSISTENCE_TOPIC;
import static org.openremote.manager.server.asset.AssetPredicates.isPersistenceEventForEntityType;
import static org.openremote.model.asset.AssetType.THING;

/**
 * Process asset attribute changes, routing asset-related messages.
 *
 * Receives {@link AttributeEvent} messages in {@link #updateAttributeValue(AttributeEvent)} and processes them.
 * <p>
 * {@link AttributeEvent} messages can come from various sources:
 *
 * <ul>
 * <li>Protocol {@link org.openremote.agent3.protocol.AbstractProtocol#onSensorUpdate(AttributeState, long)}</li>
 * <li>User/Client initiated</li>
 * <li>Rules</li>
 * </ul>
 *
 * <p>
 * The {@link AttributeEvent} messages are first validated (link and value type checking) then they are
 * converted into {@link AssetUpdate} messages which are then passed through the processing chain of
 * {@link Consumer&lt;AssetUpdate&gt;}.
 *
 * <p>
 * The regular processing chain is:
 * <ul>
 * <li>{@link RulesService}</li>
 * <li>{@link AgentService}</li>
 * <li>{@link AssetStorageService}</li>
 * <li>{@link AssetDatapointService}</li>
 * </ul>
 *
 * <p>
 * Rules Service processing logic:
 * <p>
 * Checks if attribute has {@link org.openremote.model.asset.AssetMeta#RULES_FACT} meta item with value of true and if
 * it does then the message is passed through the rule engines that are in scope for the asset. Rules have the ability
 * to change the status and new value of {@link AssetUpdate} messages to either prevent them from progressing through
 * the processing chain or changing the value that progresses through the processing chain. Rules can also set a status
 * of {@link AssetUpdate.Status#RULES_HANDLED} which means that the message shouldn't be processed by any more rule
 * engines but it should continue through the processing chain.
 *
 * <p>
 * Agent service processing logic:
 * <p>
 * When the incoming messages come from a Protocol (i.e. generated by a call from
 * {@link org.openremote.agent3.protocol.AbstractProtocol#onSensorUpdate(AttributeState, long)} then
 * the Agent Service will ignore the message and just pass it onto the next consumer.
 *
 * When the incoming messages come from any other source then the Agent Service will check if it relates
 * to a THING asset and if so it will check if the attribute is linked to an agent. If it is not linked to
 * an Agent then it ignores the message and just passes it to the next consumer. If it is linked to an Agent
 * and the Agent link is invalid then the message status is set to {@link AssetUpdate.Status#ERROR} and
 * the message will not be able to progress through the processing chain.
 *
 * If the message is for a valid linked agent then a message is sent on the
 * {@link org.openremote.agent3.protocol.AbstractProtocol#ACTUATOR_TOPIC} which the Protocol will receive in
 * {@link org.openremote.agent3.protocol.AbstractProtocol#sendToActuator(AttributeEvent)}.
 *
 * <p>
 * This means that a protocol implementation is responsible for producing a new {@link AttributeEvent} to
 * indicate to the system that the attribute value has/has not changed. The protocol should know best when to
 * do this and will vary from protocol to protocol; some 'things' might respond to an actuator command, or they
 * might send a separate sensor changed message or both or neither (fire and forget) the protocol must decide
 * what the best course of action is based on the 'things' it communicates with and the transport layer it uses etc.
 * <p>
 *
 * <p>
 * Asset Storage Service processing logic:
 * <p>
 * Always tries to persist the attribute value in the DB and allows the message to continue if the commit was
 * successful.
 *
 * <p>
 * Asset Datapoint Service processing logic:
 * <p>
 * Checks if attribute has {@link org.openremote.model.asset.AssetMeta#STORE_DATA_POINTS} meta item with a value of true
 * and if it does then the {@link AttributeEvent} is stored in a time series DB. Then allows the message to continue
 * if the commit was successful.
 */
public class AssetProcessingService extends RouteBuilder implements ContainerService {

    private static final Logger LOG = Logger.getLogger(AssetProcessingService.class.getName());

    protected RulesService rulesService;
    protected AgentService agentService;
    protected AssetStorageService assetStorageService;
    protected AssetDatapointService assetDatapointService;
    protected MessageBrokerService messageBrokerService;

    final protected List<Consumer<AssetUpdate>> processors = new ArrayList<>();

    @Override
    public void init(Container container) throws Exception {
        rulesService = container.getService(RulesService.class);
        agentService = container.getService(AgentService.class);
        assetStorageService = container.getService(AssetStorageService.class);
        assetDatapointService = container.getService(AssetDatapointService.class);
        messageBrokerService = container.getService(MessageBrokerService.class);

        processors.add(rulesService);
        processors.add(agentService);
        processors.add(assetStorageService);
        processors.add(assetDatapointService);

        container.getService(MessageBrokerSetupService.class).getContext().addRoutes(this);
    }

    @Override
    public void start(Container container) throws Exception {

    }

    @Override
    public void stop(Container container) throws Exception {

    }

    @Override
    public void configure() throws Exception {

        // Sensor updates are processed first by rules, then stored in the asset and datapoint databases
        from(SENSOR_TOPIC)
            .filter(body().isInstanceOf(AttributeEvent.class))
            .process(exchange -> {
                processSensorUpdate(exchange.getIn().getBody(AttributeEvent.class));
            });

        // If any asset was modified in the database, detect changed attributes
        from(PERSISTENCE_TOPIC)
            .filter(isPersistenceEventForEntityType(Asset.class))
            .process(exchange -> {
                PersistenceEvent persistenceEvent = exchange.getIn().getBody(PersistenceEvent.class);
                Asset asset = (Asset) persistenceEvent.getEntity();
                // TODO: Detect which attribute was created/updated in the database and handle it
            });
    }

    /**
     * This is the entry point for any attribute value change event in the entire system. This deals
     * with single attribute value changes and pushes them through the attribute event processing chain
     * where each consumer is given the opportunity to consume the event or allow it progress to the
     * next consumer {@link AssetUpdate.Status}.
     *
     * NOTE: An attribute value can be changed during Asset CRUD but this does not come through
     * this route but is handled separately see {@link AssetResourceImpl}. Any attribute values
     * assigned during Asset CRUD can be thought of as the attributes initial value and is subject
     * to change by the following actors (depending on attribute meta etc.) all actors use this
     * entry point to initiate an attribute value change:
     *
     * Rules
     * Protocol
     * User
     *
     * @param attributeEvent
     */
    public void updateAttributeValue(AttributeEvent attributeEvent) {

        // Check this event relates to a valid asset
        ServerAsset asset = assetStorageService.find(attributeEvent.getEntityId());

		if (asset == null) {
			LOG.warning("Processing client update failed asset not found: " + attributeEvent);
			return;
		}

		// Prevent editing of individual agent attributes
        if (asset.getWellKnownType() == AssetType.AGENT) {
            throw new RuntimeException("Agent attributes can not be updated individually, update the whole asset instead");
        }

        // Pass attribute event through the processing chain
        LOG.fine("Processing client " + attributeEvent + " for: " + asset);
        Attributes attributes = new Attributes(asset.getAttributes());
        Attribute attribute = attributes.get(attributeEvent.getAttributeName());

        if (attribute == null) {
            LOG.warning("Ignoring " + attributeEvent + ", attribute doesn't exist on asset: " + asset);
            return;
        }

        // Prevent editing of read only attributes
        if (attribute.isReadOnly()) {
            LOG.warning("Ignoring " + attributeEvent + ", attribute is read-only in: " + asset);
            return;
        }

        processUpdate(asset, attribute, attributeEvent);
    }

    /**
     * We get here if a protocol pushes a sensor update message.
     *
     * @param attributeEvent
     */
    protected void processSensorUpdate(AttributeEvent attributeEvent) {
        // Must reference a thing asset
        ServerAsset thing = assetStorageService.find(attributeEvent.getEntityId());
        if (thing.getWellKnownType() != THING) {
            LOG.fine("Ignoring " + attributeEvent + ", not a thing: " + thing);
            return;
        }

        LOG.fine("Processing sensor " + attributeEvent + " for thing: " + thing);

        // Get the attribute and check it is actually linked to an agent (although the
        // event comes from a Protocol, we can not assume that the attribute is still linked,
        // consider a protocol that receives a batch of messages because a gateway was offline
        // for a day)
        ThingAttributes thingAttributes = new ThingAttributes(thing);
        ThingAttribute thingAttribute = thingAttributes.getLinkedAttribute(
            assetStorageService.getAgentLinkResolver(), attributeEvent.getAttributeName()
        );

        if (thingAttribute == null) {
            LOG.warning("Processing sensor update failed attribute not linked to an agent: " + attributeEvent);
            return;
        }

        // Protocols can write to readonly attributes (i.e. sensor attributes)
        // So no need to check readonly flag

        processUpdate(thing, thingAttribute, attributeEvent);
    }

    protected void processUpdate(ServerAsset asset,
                                 Attribute attribute,
                                 AttributeEvent attributeEvent) {
        // Ensure timestamp of event is not in the future as that would essentially block access to
        // the attribute until after that time (maybe that is desirable behaviour)
        // Allow a leniency of 1s
        if (attributeEvent.getTimestamp() - System.currentTimeMillis() > 1000) {
            // TODO: Decide how to handle update events in the future - ignore or change timestamp
            LOG.warning("Ignoring " + attributeEvent + ", event-time is in the future in:" + asset);
            return;
        }

        // Hold on to existing attribute state so we can use it during processing
        AttributeEvent lastStateEvent = attribute.getStateEvent(asset.getId());

        // Check the last update timestamp of the attribute, ignoring any event that is older than last update
        // TODO: This means we drop out-of-sequence events, we might need better at-least-once handling
        if (lastStateEvent.getTimestamp() >= 0 && attributeEvent.getTimestamp() <= lastStateEvent.getTimestamp()) {
            LOG.warning("Ignoring " + attributeEvent + ", event-time is older than attribute's last state " + lastStateEvent + " in: " + asset);
            return;
        }

        // Set new value and event timestamp on attribute, thus validating any attribute constraints
        try {
            attribute.applyStateEvent(attributeEvent);
        } catch (IllegalArgumentException ex) {
            LOG.log(Level.WARNING, "Ignoring " + attributeEvent + ", attribute constraint violation in: " + asset, ex);
            return;
        }

        processUpdate(new AssetUpdate(asset, attribute, attributeEvent, lastStateEvent));
    }

    protected void processUpdate(AssetUpdate assetUpdate) {
        for (Consumer<AssetUpdate> processor : processors) {
            try {
                LOG.fine("Processor " + processor + " accepts: " + assetUpdate);
                processor.accept(assetUpdate);
            } catch (Throwable t) {
                LOG.log(Level.SEVERE, "Asset update consumer '" + processor + "' threw an exception whilst consuming the update:" + assetUpdate, t);
                assetUpdate.setStatus(AssetUpdate.Status.ERROR);
                assetUpdate.setError(t);
            }

            switch (assetUpdate.getStatus()) {
                case HANDLED:
                    LOG.fine("Processor " + processor + " finally handled: " + assetUpdate);
                    return;
                case ERROR:
                    // TODO Better error handling, not sure we need rewind?
                    LOG.severe("Asset update status is '" + assetUpdate.getStatus() + "' cannot continue processing");
                    assetUpdate.setStatus(AssetUpdate.Status.COMPLETED);
                    throw new RuntimeException("Processor " + processor + " error: " + assetUpdate, assetUpdate.getError());
            }
        }
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" +
            '}';
    }
}
