name: Build manager image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
    inputs:
      skip:
        type: boolean
        description: Skip condition to allow branch protection checks to pass
        default: false
      TAGS:
        type: string
        default: ""
        description: Comma separated list of docker image tags

jobs:
  build-manager-image:
    name: Manager image
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: or-manager-build
          path: manager/build

      - name: Install QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          platforms: linux/amd64,linux/aarch64

      - name: Install Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Parse tags and evaluate conditions
        id: meta
        shell: bash
        run: |
          COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)

          FORMATTED_TAGS="openremote/manager:$COMMIT_SHA_SHORT"
          FIRST_TAG="openremote/manager:$COMMIT_SHA_SHORT"
          SHOULD_PUSH="false"

          if [ -n "${{ inputs.TAGS }}" ]; then
            SHOULD_PUSH="true"

            IFS=',' read -ra TAGS <<< "${{ inputs.TAGS }}"
            for tag in "${TAGS[@]}"; do
              CLEAN_TAG=$(echo "$tag" | xargs)
              FULL_TAG="openremote/manager:$CLEAN_TAG"

              # Make the first explicit tag our primary reference
              if [ "$FIRST_TAG" == "openremote/manager:$COMMIT_SHA_SHORT" ]; then
                FIRST_TAG=$FULL_TAG
              fi

              FORMATTED_TAGS="$FORMATTED_TAGS,$FULL_TAG"
            done
          fi

          echo "formatted_tags=$FORMATTED_TAGS" | tee -a $GITHUB_OUTPUT
          echo "first_tag=$FIRST_TAG" | tee -a $GITHUB_OUTPUT
          echo "should_push=$SHOULD_PUSH" | tee -a $GITHUB_OUTPUT

      - name: Build and load manager image for Grype scan
        timeout-minutes: 20
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: manager/build/install/manager
          platforms: linux/amd64 # "ubuntu-latest" runs on x86 GitHub runners
          load: true # Load image locally for Grype Scan
          push: false
          tags: ${{ steps.meta.outputs.formatted_tags }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          cache-from: type=gha,scope=manager
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Scan manager docker image
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        id: manager-anchore-scan
        with:
          image: ${{ steps.meta.outputs.first_tag }}
          fail-build: true
          severity-cutoff: critical

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        if: ${{ always() && steps.meta.outputs.should_push == 'true' }}
        with:
          sarif_file: ${{ steps.manager-anchore-scan.outputs.sarif }}

      - name: Inspect Anchore scan SARIF report
        if: ${{ always() && steps.meta.outputs.should_push == 'true' }}
        run: cat ${{ steps.manager-anchore-scan.outputs.sarif }}

      - name: Login to DockerHub
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        if: ${{ success() && steps.meta.outputs.should_push == 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build multi-platform manager image
        timeout-minutes: 20
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: manager/build/install/manager
          platforms: linux/amd64,linux/aarch64
          load: false
          push: ${{ steps.meta.outputs.should_push == 'true' }}
          tags: ${{ steps.meta.outputs.formatted_tags }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          cache-from: type=gha,scope=manager
          cache-to: type=gha,mode=max,scope=manager
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
