# Currently only used to test if it builds before merging to master
name: Build deployment image

on:
  workflow_call:
    inputs:
      skip:
        type: boolean
        description: Skip condition to allow branch protection checks to pass
        default: false
      tag:
        type: string
        required: true

jobs:
  build-deployment-image:
    name: Deployment image
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up JDK 21 and Gradle cache
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"

      - name: Check deployment build.gradle
        id: check_deployment_gradle
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          fail: true # Deployment must have a build.gradle file to prepare the deployment files in the deployment/build dir
          files: "deployment/build.gradle"

      - name: Check deployment dockerfile
        id: check_deployment_dockerfile
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          fail: true
          files: "deployment/Dockerfile"

      - name: Build deployment
        shell: bash
        run: ./gradlew -p deployment installDist # TODO: optimize the task graph

      - name: Install QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: linux/amd64,linux/aarch64
      - name: Install Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Build deployment image
        timeout-minutes: 20
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: deployment/build
          platforms: linux/amd64,linux/aarch64
          load: false
          push: false
          tags: openremote/deployment:${{ inputs.tag }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
