# Currently only used to test if it builds before merging to master
name: Build deployment image

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build-deployment-image:
    name: Deployment image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: or-deployment-build
          path: deployment/build
      - name: Install QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: linux/amd64,linux/aarch64
      - name: Install Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Build deployment image
        timeout-minutes: 20
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: deployment/build
          platforms: linux/amd64,linux/aarch64
          load: false
          push: false
          tags: openremote/deployment:${{ inputs.tag }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
