name: Custom staging

on:
  workflow_dispatch:
    inputs:
      PUSH_SNAPSHOT:
        description: "Push snapshot Docker image to AWS ECR"
        type: boolean

jobs:
  detect-changes:
    name: Detect whether code changed
    runs-on: ubuntu-latest
    outputs: # See https://github.com/tj-actions/changed-files/tree/2bb135777322059ee3a3c9239999b159ff49febc#outputs-
      any_modified: ${{ steps.changed-files.outputs.backend_any_modified == 'true' || steps.changed-files.outputs.ui_any_modified == 'true' }}
      backend_any_modified: ${{ steps.changed-files.outputs.backend_any_modified }}
      ui_any_modified: ${{ steps.changed-files.outputs.ui_any_modified }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2 # Must be 2 for push events to compare to previous commit
      - name: Detect changes
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files_yaml: |
            ui:
              - 'ui/**'
              - '!**/*.md'
              - '!**/*.yml'
            backend:
              - '!.ci_cd/**'
              - '!deployment/**'
              - '!**/*.md'
              - '!**/*.yml'
              - '!yarn.lock'

  install-dist:
    name: Build
    needs: detect-changes
    if: needs.detect-changes.outputs.any_modified == 'true'
    uses: "./.github/workflows/install-dist.yml"

  unit-tests:
    name: Test
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_any_modified == 'true'
    uses: "./.github/workflows/unit-tests.yml"

  integration-tests:
    name: Test
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_any_modified == 'true'
    uses: "./.github/workflows/integration-tests.yml"

  code-coverage:
    name: Test
    needs: [unit-tests, integration-tests]
    if: needs.detect-changes.outputs.backend_any_modified == 'true'
    uses: "./.github/workflows/code-coverage.yml"

  # deployment:
  #   name: Deploy
  #   needs: [unit-tests, integration-tests]
  #   uses: "./.github/workflows/deployment.yml"
