name: Deployment
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: Environment (.env) file to use.
        type: string
        required: false
      hostname:
        description: Instance to deploy to.
        type: string
        required: true
      password:
        description: Configure OR_ADMIN_PASSWORD or override .env value
        type: string
        required: false
      clean_install:
        description: Delete Docker volumes (manager / postgres data)
        type: boolean
        default: false

jobs:
  deployment:
    name: "Deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - run: echo 'test'
