name: Install Dist

on:
  workflow_call:
    inputs:
      COMMIT:
        type: string
        description: 'Repo branch or commit SHA to checkout'
      skip:
        type: boolean
        description: Skip condition to allow branch protection checks to pass
        default: false
      VERSION_WITH_QUALIFIER:
        type: string
    outputs:
      npmTag:
        description: The NPM package.json version
        value: ${{ jobs.install-dist.outputs.npmTag }}

jobs:
  install-dist:
    name: Install Dist
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    outputs:
      npmTag: ${{ steps.update-package-json.outputs.tag }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.COMMIT }}
          lfs: true # Enable Git LFS plugin to fetch *.mbtiles

      - name: Check if main repo
        id: is_main_repo
        uses: openremote/openremote/.github/actions/check-if-main-repo@fa6f52032b1dea3d4ad080cc6436a3ef3843b0be

      - name: Set up JDK 21 and Gradle cache
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Update version in package.json files
        id: update-package-json
        if: ${{ inputs.VERSION_WITH_QUALIFIER != '' }}
        run: |
          VERSION=$(awk '{print tolower($0)}' <<< $VERSION)

          QUALIFIER=$(sed -E 's/.+-([a-z]+).*/\1/g' <<< $VERSION)
          if [ "$QUALIFIER" == "$VERSION" ]; then
            QUALIFIER=""
          fi

          if [ "$QUALIFIER" == "" ]; then
            TAG="latest"
          else
            if [ "$QUALIFIER" == "snapshot" ]; then
              # Add a timestamp to snapshot versions
              VERSION="$VERSION.$(date +'%Y%m%d%H%M%S')"
            else
              # Separate qualifiers from numbers of alpha, beta, rc versions
              VERSION=$(sed "s/$QUALIFIER/$QUALIFIER./g" <<< $VERSION)
            fi
            TAG="$QUALIFIER"
          fi

          find ui -maxdepth 3 -name package.json | xargs -I{} sed -i -E "s#\"version\": \".+\",#\"version\": \"$VERSION\",#" {}

          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ inputs.VERSION_WITH_QUALIFIER }}

      - name: Run Install Dist
        timeout-minutes: 20
        run: ./gradlew installDist -x :deployment:installDist

      - name: Archive manager build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: or-manager-build
          if-no-files-found: error
          path: |
            manager/build

      - name: Archive UI component build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: or-ui-component-build
          if-no-files-found: error
          path: |
            ui/component/model/src/model.ts
            ui/component/rest/src/restclient.ts
            ui/component/**/custom-elements.json
            ui/component/**/custom-elements-jsx.d.ts
            ui/component/**/dist
            ui/component/**/lib
            ui/component/**/tsconfig.tsbuildinfo
            ui/component/**/package.json

      - name: Archive UI app build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: or-ui-app-build
          if-no-files-found: error
          path: |
            ui/app/**/dist
            ui/app/**/lib
            ui/app/**/package.json

      - name: Archive UI util build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: or-ui-util-build
          if-no-files-found: error
          path: |
            ui/util/package.json

      - name: Archive MDI fonts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ steps.is_main_repo.outputs.value == 'true' }}
        with:
          name: mdi-fonts
          if-no-files-found: error
          path: |
            ui/app/shared/fonts/Material Design Icons
