name: NPM publish dry run
on: workflow_call

jobs:
  npm-dry-run:
    name: NPM publish dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8
        with:
          name: or-ui-component-build
          path: ui/component
      - name: Update when the `tsbuildinfo` files were last modified to 'now'
        run: find . -name "*.tsbuildinfo" -exec touch {} +
        # You can see how the TypeScript compiler invalidates the build artifacts by running:
        # - `npx tsc -b --verbose`: to see if the artifacts are up-to-date
        # - `find src | xargs touch`: to update component inputs
      - run: yarn --immutable
      - name: Run NPM publish dry run
        timeout-minutes: 20
        run: yarn workspaces foreach --all --no-private --topological npm publish --dry-run
