name: Review

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect whether code changed
    runs-on: ubuntu-latest
    outputs: # See https://github.com/tj-actions/changed-files/tree/2bb135777322059ee3a3c9239999b159ff49febc#outputs-
      any_modified: ${{ steps.changed-files.outputs.backend_any_modified == 'true' || steps.changed-files.outputs.ui_any_modified == 'true' }}
      backend_any_modified: ${{ steps.changed-files.outputs.backend_any_modified }}
      ui_any_modified: ${{ steps.changed-files.outputs.ui_any_modified }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Detect changes
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files_yaml: |
            ui:
              - '.yarn'
              - 'ui/**'
              - '!**/*.md'
              - '!**/*.yml'
              - '.yarnrc.yml'
              - 'package.json'
              - 'yarn.lock'
            backend:
              - '!.ci_cd/**'
              - '!.yarn'
              - '!deployment/**'
              - '!ui/**'
              - '!**/*.md'
              - '!**/*.yml'
              - '!.yarnrc.yml'
              - '!package.json'
              - '!yarn.lock'

  ui-check-dependencies:
    name: Lint
    needs: detect-changes
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/ui-check-dependencies.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.ui_any_modified != 'true' }}

  ui-check-outdated-translations:
    name: Lint
    needs: detect-changes
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/ui-check-outdated-translations.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.backend_any_modified != 'true' }}

  install-browsers:
    name: Build
    needs: detect-changes
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/install-browsers.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.any_modified != 'true' }}

  install-dist:
    name: Build
    needs: detect-changes
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/install-dist.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.any_modified != 'true' }}

  unit-tests:
    name: Test
    needs: detect-changes
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/unit-tests.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.backend_any_modified != 'true' }}

  integration-tests:
    name: Test
    needs: detect-changes
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/integration-tests.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.backend_any_modified != 'true' }}

  code-coverage:
    name: Test
    needs: [detect-changes, unit-tests, integration-tests]
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/code-coverage.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.backend_any_modified != 'true' }}

  ui-component-tests:
    name: Test
    needs: [detect-changes, install-dist, install-browsers]
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/ui-component-tests.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.ui_any_modified != 'true' }}

  ui-app-tests:
    name: Test
    needs: [detect-changes, install-dist, install-browsers]
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/ui-app-tests.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.any_modified != 'true' }}

  build-manager-image:
    name: Build
    needs: [detect-changes, install-dist]
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/build-manager-image.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.any_modified != 'true' }}
    secrets:
      DOCKERHUB_USER: ${{ secrets._TEMP_DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets._TEMP_DOCKERHUB_PASSWORD }}

  build-deployment-image: # Only here to check if it can build successfully
    name: Build
    needs: [detect-changes, install-dist]
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/build-deployment-image.yml"
    with:
      tag: develop
      skip: ${{ needs.detect-changes.outputs.any_modified != 'true' }}

  publish-npm-dry-run:
    name: Publish
    needs: [detect-changes, install-dist]
    if: ${{ !failure() && !cancelled() }}
    uses: "./.github/workflows/publish-npm-dry-run.yml"
    with:
      skip: ${{ needs.detect-changes.outputs.ui_any_modified != 'true' }}

  get-version-details: # Only here to check if it can build successfully
    name: Build / Get version details
    needs: install-dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Get version details
        id: get-version-details
        uses: openremote/openremote/.github/actions/get-version-details@fa6f52032b1dea3d4ad080cc6436a3ef3843b0be
