name: Staging

on:
  workflow_dispatch:
    inputs:
      PUSH_SNAPSHOT:
        description: 'Push snapshot Docker image to AWS ECR'
        type: boolean

jobs:

  detect-changes:
    name: Detect whether code changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Detect changes
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files_yaml: |
            ui:
              - 'ui/**'
              - '!**/*.md'
              - '!**/*.yml'
            backend:
              - '!.ci_cd/**'
              - '!deployment/**'
              - '!**/*.md'
              - '!**/*.yml'
              - '!yarn.lock'

  ui-check-dependencies:
    name: Lint
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/ui-check-dependencies.yml'

  ui-check-outdated-translations:
    name: Lint
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/ui-check-outdated-translations.yml'

  install-dist:
    name: Build
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/install-dist.yml'

  unit-tests:
    name: Test
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/unit-tests.yml'

  integration-tests:
    name: Test
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/integration-tests.yml'

  ui-component-tests:
    name: Test
    needs: [detect-changes, install-dist]
    #if: needs.detect-changes.outputs.ui_any_changed == 'true'
    uses: './.github/workflows/ui-component-tests.yml'

  ui-app-tests:
    name: Test
    needs: [detect-changes, install-dist]
    uses: './.github/workflows/ui-app-tests.yml'

  build-manager-image:
    name: Build
    needs: [detect-changes, install-dist]
    uses: './.github/workflows/build-manager-image.yml'
    secrets:
      DOCKERHUB_USER: ${{ secrets._TEMP_DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets._TEMP_DOCKERHUB_PASSWORD }}

  build-deployment-image:
    name: Build
    needs: [ install-dist ]
    uses: './.github/workflows/build-deployment-image.yml'

  build-snapshot-image:
    name: Build
    if: ${{ inputs.PUSH_SNAPSHOT == 'true' }}
    needs: [ detect-changes, install-dist ]
    uses: './.github/workflows/build-snapshot-image.yml'
    secrets:
      AWS_DEVELOPERS_ACCOUNT_ID: ${{ secrets.OR_AWS_DEVELOPERS_ACCOUNT_ID }}
      AWS_ECR_PUSH_ROLE: ${{ secrets.OR_GH_AWS_ECR_PUSH_ROLE }}

  update-package-json:
    name: Build
    needs: detect-changes
    uses: './.github/workflows/update-package-json.yml'

  publish-maven:
    name: Publish
    needs: [ui-check-outdated-translations]
    uses: './.github/workflows/publish-maven.yml'
    secrets:
      MAVEN_SIGNING_PASSWORD: ${{ secrets._TEMP_MAVEN_SIGNING_PASSWORD }}
      MAVEN_SIGNING_KEY: ${{ secrets._TEMP_MAVEN_SIGNING_KEY }}
      MAVEN_USERNAME: ${{ secrets._TEMP_MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets._TEMP_MAVEN_PASSWORD }}

  publish-npm-dry-run:
    name: Publish
    needs: detect-changes
    uses: './.github/workflows/publish-npm-dry-run.yml'

  publish-npm:
    name: Publish
    needs: [update-package-json]
    uses: './.github/workflows/publish-npm.yml'
    with:
      tag: ${{ needs.update-package-json.outputs.tag }}
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets._TEMP_NPM_AUTH_TOKEN }}

  deployment:
    name: Deploy
    needs: [ build-deployment-image ]
    uses: './.github/workflows/deployment.yml'




