name: Staging

on:
  workflow_dispatch:

jobs:

  detect-changes:
    name: Detect whether code changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Detect changes
        id: detect-changes
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files_yaml: |
            ui:
              - 'ui/**'
              - '!**/*.md'
              - '!**/*.yml'
            backend:
              - '!.ci_cd/**'
              - '!deployment/**'
              - '!**/*.md'
              - '!**/*.yml'
              - '!yarn.lock'

  ui-check-dependencies:
    name: Lint
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/ui-check-dependencies.yml'

  install-dist:
    name: Build
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/install-dist.yml'

  unit-tests:
    name: Test
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/unit-tests.yml'

  integration-tests:
    name: Test
    needs: detect-changes
    #if: needs.detect-changes.outputs.changed == 'true'
    uses: './.github/workflows/integration-tests.yml'

  component-tests:
    name: Test
    needs: [detect-changes, install-dist]
    #if: needs.detect-changes.outputs.ui_any_changed == 'true'
    uses: './.github/workflows/ui-component-tests.yml'

  app-tests:
    name: Test
    needs: [detect-changes, install-dist]
    uses: './.github/workflows/ui-app-tests.yml'

  docker-manager-image:
    name: Docker
    needs: [detect-changes, install-dist]
    uses: './.github/workflows/docker-manager-image.yml'
    secrets:
      DOCKERHUB_USER: ${{ secrets._TEMP_DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets._TEMP_DOCKERHUB_PASSWORD }}

  docker-deployment-image:
    name: Docker
    needs: [ install-dist ]
    uses: './.github/workflows/docker-deployment-image.yml'

  deployment:
    name: Deployment
    needs: [ docker-deployment-image ]
    uses: './.github/workflows/deployment.yml'




