name: Deploy to Hetzner Cloud

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: "Name of the instance"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.0"

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        id: terraform
        run: terraform apply -auto-approve -var="hcloud_token=${{ secrets.HETZNER_API_TOKEN }}" -var="instance_name=${{ github.event.inputs.instance_name }}"
        env:
          HETZNER_API_TOKEN: ${{ secrets.HETZNER_API_TOKEN }}

      - name: Wait for server to be ready
        run: |
          echo "Waiting for OpenRemote service to be ready..."
          until curl --output /dev/null --silent --head --fail --max-time 10 https://${{ steps.terraform.outputs.server_ip }}; do
            echo "Waiting for HTTPS service to be available..."
            sleep 10
          done
          echo "Server is ready with enabled. IP: ${{ steps.terraform.outputs.server_ip }}"
