name: UI Check Dependencies
on:
  workflow_call:
    inputs:
      skip:
        type: boolean
        description: Skip condition to allow branch protection checks to pass
        default: false

jobs:
  ui-check-dependencies:
    name: UI Check Dependencies
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK 21 and gradle cache
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Check UI dependencies
        timeout-minutes: 20
        run: ./gradlew knip
