name: UI Check Dependencies
on:
  workflow_call:
    inputs:
      skip:
        type: boolean
        description: Skip condition to allow branch protection checks to pass
        default: false

jobs:
  ui-check-dependencies:
    name: UI Check Dependencies
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up JDK 21 and gradle cache
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Check UI dependencies
        timeout-minutes: 20
        run: ./gradlew knip
