name: Unit Tests
on:
  workflow_call:
    inputs:
      skip:
        type: boolean
        description: Skip condition to allow branch protection checks to pass
        default: false

jobs:
  unit-tests:
    name: Unit Tests
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK 21 and Gradle cache
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Check if main repo
        id: is_main_repo
        uses: openremote/openremote/.github/actions/check-if-main-repo@fa6f52032b1dea3d4ad080cc6436a3ef3843b0be

      - name: Run unit tests
        timeout-minutes: 20
        run: |
          if [ "${{ steps.is_main_repo.outputs.value }}" = "true" ]; then
            ./gradlew test -x :test:test -x npmTest unitTestReport
          else
            ./gradlew test -x :test:test
          fi

      - name: Archive unit test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: or-unit-test-results
          path: build/reports/tests/test/aggregated-results/

      - name: Archive JaCoCo coverage outputs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: or-unit-test-outputs
          path: |
            **/build/classes/java/main/**
            **/build/classes/java/test/**
            **/build/jacoco/*.exec
            **/build/reports/tests/test/**
            **/build/test-results/test/**
