name: Update version in package.json files
on:
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.update-package-json.outputs.tag }}
      version:
        value: ${{ jobs.update-package-json.outputs.version }}

jobs:
  update-package-json:
    name: Update version in package.json files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Get version details
        id: get-version-details
        run: |
          ./gradlew currentVersion | tee /tmp/currentVersion
          versionWithQualifier=$(grep "Project version" /tmp/currentVersion | sed 's#Project version: ##')
          version=$(sed -E 's#-.+##' <<< $versionWithQualifier)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "version_with_qualifier=$versionWithQualifier" >> $GITHUB_OUTPUT
      - name: Update version in package.json files
        id: update-package-json-files
        run: |
          VERSION=$(awk '{print tolower($0)}' <<< $VERSION)

          QUALIFIER=$(sed -E 's/.+-([a-z]+).*/\1/g' <<< $VERSION)
          if [ "$QUALIFIER" == "$VERSION" ]; then
            QUALIFIER=""
          fi

          if [ "$QUALIFIER" == "" ]; then
            TAG="latest"
          else
            if [ "$QUALIFIER" == "snapshot" ]; then
              # Add a timestamp to snapshot versions
              VERSION="$VERSION.$(date +'%Y%m%d%H%M%S')"
            else
              # Separate qualifiers from numbers of alpha, beta, rc versions
              VERSION=$(sed "s/$QUALIFIER/$QUALIFIER./g" <<< $VERSION)
            fi
            TAG="$QUALIFIER"
          fi

          find ui -maxdepth 3 -name package.json | xargs -I{} sed -i -E "s#\"version\": \".+\",#\"version\": \"$VERSION\",#" {}

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ steps.get-version-details.outputs.version_with_qualifier }}
